### ISSUE TITLE
0xdeadbeef - No strict check of `msg.value` in `_createPool` can result in loss of funds when `baseFee` is updated.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#112]
0xdeadbeef

high

# No strict check of `msg.value` in `_createPool` can result in loss of funds when `baseFee` is updated.

`_createPool` makes sure that `msg.value` is **HIGHER** then amount to fund and `baseFee`.
However - `baseFee` if updatable and can decrease. If a decreasing update is in the same block as a creation of a pool, the innocent pool creator will lose more `baseFee` then needed.

## Vulnerability Detail

```solidity
    function _createPool(
        bytes32 _profileId,
        IStrategy _strategy,
        bytes memory _initStrategyData,
        address _token,
        uint256 _amount,
        Metadata memory _metadata,
        address[] memory _managers
    ) internal returns (uint256 poolId) {
------
        if (baseFee > 0) {
            // To prevent paying the baseFee from the Allo contract's balance
            // If _token is NATIVE, then baseFee + _amount should be >= than msg.value.
            // If _token is not NATIVE, then baseFee should be >= than msg.value.
            if ((_token == NATIVE && (baseFee + _amount >= msg.value)) || (_token != NATIVE && baseFee >= msg.value)) {
                revert NOT_ENOUGH_FUNDS();
            }
            _transferAmount(NATIVE, treasury, baseFee);
            emit BaseFeePaid(poolId, baseFee);
        }
------
    }

    function updateBaseFee(uint256 _baseFee) external onlyOwner {
        _updateBaseFee(_baseFee);
    }
```

As seen above in `_createPool` function - `msg.value` is checked to be above the `baseFee`.
If `updateBaseFee` is called in the same block. An innocent pool creator will not be aware of the change (since the block is not finalized and the creation can be after the update) and will send a `msg.value` with the previous `baseFee` (not a user error).

The funds will be accepted and not refunded.

## Impact

Loss of funds

## Tool used

Manual Review

## Recommendation

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L423
In `_createPool` change the if statements as follows:
```solidity
        if (baseFee > 0) {
            // To prevent paying the baseFee from the Allo contract's balance
            // If _token is NATIVE, then baseFee + _amount should be >= than msg.value.
            // If _token is not NATIVE, then baseFee should be >= than msg.value.
            if ((_token == NATIVE && (baseFee + _amount != msg.value)) || (_token != NATIVE && baseFee != msg.value)) {
                revert FUNDS_NOT_ACCURATE();
            }
            _transferAmount(NATIVE, treasury, baseFee); 
            emit BaseFeePaid(poolId, baseFee);
        }
        else {
            if (_token != NATIVE && msg.value != 0) revert FUNDS_NOT_ACCURATE()
        }
```

**Comment by 0xdeadbeef0x** [comment]
Escalate

I am claiming that this is a valid issue that can result in loss of funds.
In a living active protocol this can impact multiple pool creators.

Please re-read my submission and consider accepting it as there is loss of funds and can happen.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I am claiming that this is a valid issue that can result in loss of funds.
> In a living active protocol this can impact multiple pool creators.
> 
> Please re-read my submission and consider accepting it as there is loss of funds and can happen.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by thelostone-mc** [comment]
Duplicate of https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/228

**Comment by neeksec** [comment]
See #228 for validity.

**Comment by Evert0x** [comment]
Planning to duplicate with #228, @0xdeadbeef0x, feel free to comment on my last question on #228 as well.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xdeadbeef0x](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/112/#issuecomment-1765704618): rejected
