### ISSUE TITLE
0xdeadbeef - Users are forced to overpay when creating a pool

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#114]
0xdeadbeef

high

# Users are forced to overpay when creating a pool

`Allo` uses the `baseFee` as a flat payment to the treasury on pool creation. However the code requires that a user passes a `msg.value` that is higher then the `baseFee` thus overpaying.

## Vulnerability Detail
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L423
```solidity
    function _createPool(
        bytes32 _profileId,
        IStrategy _strategy,
        bytes memory _initStrategyData,
        address _token,
        uint256 _amount,
        Metadata memory _metadata,
        address[] memory _managers
    ) internal returns (uint256 poolId) {
------
        if (baseFee > 0) {
            // To prevent paying the baseFee from the Allo contract's balance
            // If _token is NATIVE, then baseFee + _amount should be >= than msg.value.
            // If _token is not NATIVE, then baseFee should be >= than msg.value.
            if ((_token == NATIVE && (baseFee + _amount >= msg.value)) || (_token != NATIVE && baseFee >= msg.value)) {
                revert NOT_ENOUGH_FUNDS();
            }
            _transferAmount(NATIVE, treasury, baseFee);
            emit BaseFeePaid(poolId, baseFee);
        }
------
    }
```

See the comments and the if statements above.`>=` is used. This means that for a simple example that a pool is created with a non-native token and `msg.value` is set to `baseFee` - then the transaction will revert. The user needs to call with a higher amount of `msg.value`

## Impact

All users will always overpay.
 
## Code Snippet

There is a test already written in `Allo.t.sol`.
```solidity
    function testRevert_createPool_withBaseFee_NOT_ENOUGH_FUNDS() public {
        uint256 baseFee = 1e17;
        allo().updateBaseFee(baseFee);

        vm.expectRevert(NOT_ENOUGH_FUNDS.selector);
        _utilCreatePool(0);
    }
```

To execute run the command:
```solidity
forge test --match-test "testRevert_createPool_withBaseFee_NOT_ENOUGH_FUNDS" -v
```

Expected output:
```solidity
Running 1 test for test/foundry/core/Allo.t.sol:AlloTest
[PASS] testRevert_createPool_withBaseFee_NOT_ENOUGH_FUNDS() (gas: 367815)
Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 4.54ms
 
Ran 1 test suites: 1 tests passed, 0 failed, 0 skipped (1 total tests)
```

## Tool used

Manual Review

## Recommendation

Fix the if statement mentioned above to not revert if `msg.value` is equal to the `baseFee`

**Comment by 0xdeadbeef0x** [comment]
Escalate

This is a dup of #220 and should be marked as such. Results of escalation of 220 should be effected on this issue as well. Additionally, this should not be invalid.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is a dup of #220 and should be marked as such. Results of escalation of 220 should be effected on this issue as well. Additionally, this should not be invalid.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by neeksec** [comment]
Duplidate of #220. See #220 for validity.

**Comment by Evert0x** [comment]
Planning to reject escalation as issue is not valid and duplication requests with invalid issues are not accepted.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xdeadbeef0x](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/114/#issuecomment-1765782929): rejected
