### ISSUE TITLE
p0wd3r - The `metadata` in `RFPSimpleStrategy._registerRecipient` is not being stored.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#170]
p0wd3r

medium

# The `metadata` in `RFPSimpleStrategy._registerRecipient` is not being stored.
The `metadata` in `RFPSimpleStrategy._registerRecipient` is not being stored.
## Vulnerability Detail
The `metadata` parameter is included in `RFPSimpleStrategy._registerRecipient`, but it ultimately is not saved to the `recipient`.

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L314-L337
```solidity
    function _registerRecipient(bytes memory _data, address _sender)
        internal
        override
        onlyActivePool
        returns (address recipientId)
    {
        bool isUsingRegistryAnchor;
        address recipientAddress;
        address registryAnchor;
        uint256 proposalBid;
        Metadata memory metadata;

        // Decode '_data' depending on the 'useRegistryAnchor' flag
        if (useRegistryAnchor) {
            /// @custom:data when 'true' -> (address recipientId, uint256 proposalBid, Metadata metadata)
            (recipientId, proposalBid, metadata) = abi.decode(_data, (address, uint256, Metadata));

            // If the sender is not a profile member this will revert
            if (!_isProfileMember(recipientId, _sender)) revert UNAUTHORIZED();
        } else {
            //  @custom:data when 'false' -> (address recipientAddress, address registryAnchor, uint256 proposalBid, Metadata metadata)
            (recipientAddress, registryAnchor, proposalBid, metadata) =
                abi.decode(_data, (address, address, uint256, Metadata));
```

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L375-L379
```solidity
        // update the recipients data
        recipient.recipientAddress = recipientAddress;
        recipient.useRegistryAnchor = isUsingRegistryAnchor ? true : recipient.useRegistryAnchor;
        recipient.proposalBid = proposalBid;
        recipient.recipientStatus = Status.Pending;
```

In contrast, in `DonationVotingMerkleDistributionBaseStrategy`, the `metadata` is properly saved to the `recipient`.

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L575-L578
```solidity
        // update the recipients data
        recipient.recipientAddress = recipientAddress;
        recipient.metadata = metadata;
        recipient.useRegistryAnchor = useRegistryAnchor ? true : isUsingRegistryAnchor;
```
## Impact
The setting of the recipient's `metadata` as expected is not completed.
## Code Snippet
- https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L314-L337
- https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L375-L379
- https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L575-L578
## Tool used

Manual Review

## Recommendation
Add `recipient.metadata = metadata;`

**Comment by imp0wd3r** [comment]
Escalate

The `metadata` is crucial information. It's stored in IPFS and can contain a wealth of details, especially for frontend displays. The lack of preservation for `metadata`, in my opinion, cannot merely be rated as 'low' severity.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The `metadata` is crucial information. It's stored in IPFS and can contain a wealth of details, especially for frontend displays. The lack of preservation for `metadata`, in my opinion, cannot merely be rated as 'low' severity.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by neeksec** [comment]
Suggest to keep low.

There's no risk to the funds stored in this protocol.

**Comment by MLON33** [comment]
https://github.com/allo-protocol/allo-v2/pull/369

**Comment by Evert0x** [comment]
Planing to reject escalation and keep issue state as is. This is not a smart contract bug.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [imp0wd3r](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/170/#issuecomment-1762745968): rejected
