### ISSUE TITLE
0xdeadbeef - `Allo` and `Registry` use `AccessControl` without storage gaps which can break storage layout on upgrade

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#192]
0xdeadbeef

medium

# `Allo` and `Registry` use `AccessControl` without storage gaps which can break storage layout on upgrade

Both `Allo` and `Registry` are upgradable contracts accessed the a TransparentProxy.
When using an OZ proxy its important that all inherited contracts have storage gaps so they can be updated without causing storage layout issues

## Vulnerability Detail
`Allo`:
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L38
```solidity
---------
import "openzeppelin-contracts/contracts/access/AccessControl.sol";
import "openzeppelin-contracts-upgradeable/contracts/security/ReentrancyGuardUpgradeable.sol";
---------
contract Allo is IAllo, Native, Transfer, Initializable, Ownable, AccessControl, ReentrancyGuardUpgradeable, Errors {
```

`Registry`:
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Registry.sol#L40C14-L40C14
```solidity
---------
import {AccessControl} from "openzeppelin-contracts/contracts/access/AccessControl.sol";
import "openzeppelin-contracts-upgradeable/contracts/proxy/utils/Initializable.sol";
---------
contract Registry is IRegistry, Native, AccessControl, Transfer, Initializable, Errors {
```

As can be seen - both contracts use the non-upgradable `AccessControl.sol`which does not have storage gaps.
Any future update in `AccessControl` storage will corrupt the contract storage layout and override used slots.

## Impact

Potential storage corruption. 

## Tool used

Manual Review

## Recommendation

Use the `AccessControl` that is upgradable through `openzeppelin-contracts-upgradeable` contracts.

**Comment by 0xdeadbeef0x** [comment]
Escalate

This should be reconsidered as medium or at least low. 
1. The contracts are upgradable which shows the intent to upgrade them.
2. Historically, issues of this kind were rewarded: https://github.com/sherlock-audit/2022-09-notional-judging/issues/64

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This should be reconsidered as medium or at least low. 
> 1. The contracts are upgradable which shows the intent to upgrade them.
> 2. Historically, issues of this kind were rewarded: https://github.com/sherlock-audit/2022-09-notional-judging/issues/64

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by thelostone-mc** [comment]
Duplicate of https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/852

**Comment by neeksec** [comment]
Low per sherlock doc,
 
>Use of Storage gaps: Simple contracts with one of the parent contract not implementing storage gaps are considered low/informational. 
Exception: However, if the protocol design has a highly complex and branched set of contract inheritance with storage gaps inconsistently applied throughout and the submission clearly describes the necessity of storage gaps it can be considered a valid medium. [Example](https://github.com/sherlock-audit/2022-09-notional-judging/issues/64)

**Comment by Evert0x** [comment]
Planning to reject escalation based on the pointed out by the lead judge

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xdeadbeef0x](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/192/#issuecomment-1765793679): rejected
