### ISSUE TITLE
p0wd3r - The native tokens sent through `registerRecipient` are not passed on to the `strategy` contract.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#20]
p0wd3r

high

# The native tokens sent through `registerRecipient` are not passed on to the `strategy` contract.
The native tokens sent through `registerRecipient` are not passed on to the `strategy` contract.
## Vulnerability Detail
Both the `Allo` contract and the `BaseStrategy` contract have `registerRecipient` functions that are `payable`.
Moreover, `BaseStrategy.registerRecipient` can only be called through `Allo.registerRecipient`.

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L301-L304
```solidity
    function registerRecipient(uint256 _poolId, bytes memory _data) external payable nonReentrant returns (address) {
        // Return the recipientId (address) from the strategy
        return pools[_poolId].strategy.registerRecipient(_data, msg.sender);
    }
```

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/BaseStrategy.sol#L165-L175
```solidity
    function registerRecipient(bytes memory _data, address _sender)
        external
        payable
        onlyAllo
        onlyInitialized
        returns (address recipientId)
    {
        _beforeRegisterRecipient(_data, _sender);
        recipientId = _registerRecipient(_data, _sender);
        _afterRegisterRecipient(_data, _sender);
    }
```

In the `Allo.registerRecipient` function, the call to `strategy.registerRecipient` does not pass along `msg.value`.
```solidity
return pools[_poolId].strategy.registerRecipient(_data, msg.sender);
```

This results in the native token remaining in the Allo contract, rather than being transferred to the strategy for use.
## Impact
This results in the native token remaining in the Allo contract, rather than being transferred to the strategy for use.
## Code Snippet
- https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L301-L304
- https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/BaseStrategy.sol#L165-L175
## Tool used

Manual Review

## Recommendation
Just like in the `allocate` function, pass along `msg.value`.
```solidity
    function _allocate(uint256 _poolId, bytes memory _data) internal {
        pools[_poolId].strategy.allocate{value: msg.value}(_data, msg.sender);
    }
```

**Comment by imp0wd3r** [comment]
Escalate

The `BaseStrategy` is a foundational contract and is extendable. It cannot be guaranteed that its derived contracts won't handle native tokens.

The purpose of `BaseStrategy` is to provide a foundational framework for users to extend upon, rather than being limited to just the few strategies present in the current audit.

> The `BaseStrategy` contract serves as a foundational building block within the Allo ecosystem, forming the basis for more specialized allocation strategies. 

Moreover, both levels of functions are marked as `payable`. The documentation also doesn't state that the functions don't accept native tokens, so deeming it as a user error is quite unreasonable.

Since both `registerRecipient ` in both `Allo.sol` and `BaseStrategy.sol` are marked as `payable`, the vulnerability is plausible. If it were to occur, it could result in user assets being locked within `Allo.sol`. Therefore, it shouldn't be categorized as low risk.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The `BaseStrategy` is a foundational contract and is extendable. It cannot be guaranteed that its derived contracts won't handle native tokens.
> 
> The purpose of `BaseStrategy` is to provide a foundational framework for users to extend upon, rather than being limited to just the few strategies present in the current audit.
> 
> > The `BaseStrategy` contract serves as a foundational building block within the Allo ecosystem, forming the basis for more specialized allocation strategies. 
> 
> Moreover, both levels of functions are marked as `payable`. The documentation also doesn't state that the functions don't accept native tokens, so deeming it as a user error is quite unreasonable.
> 
> Since both `registerRecipient ` in both `Allo.sol` and `BaseStrategy.sol` are marked as `payable`, the vulnerability is plausible. If it were to occur, it could result in user assets being locked within `Allo.sol`. Therefore, it shouldn't be categorized as low risk.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0x00ffDa** [comment]
FYI, I see these duplicates: https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/925, https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/910, https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/102, https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/90, https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/40, and maybe https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/202,

**Comment by nevillehuang** [comment]
#40, #90, #102, #910, #925  are valid duplicates of this issue.

**Comment by 0xvj** [comment]
> #40, #102, #202, #294, #910, #925 and #961 are valid duplicates of this issue.

#294 , #202 are not duplicates of this issue

**Comment by neeksec** [comment]
Sugguest to keep low.

There's no security risk in current codebase.

> It cannot be guaranteed that its derived contracts won't handle native tokens.

It requires another audit if additional derived contracts are added.

**Comment by imp0wd3r** [comment]
> It requires another audit if additional derived contracts are added.

`BaseStrategy` can be extended by users, not just by the project team. Therefore, it's essential to ensure the security of `BaseStrategy` to provide users with a secure foundation.

**Comment by imp0wd3r** [comment]
> There's no security risk in current codebase.

Additionally, the main issue actually lies in Allo.sol.

**Comment by 0xvj** [comment]
> It requires another audit if additional derived contracts are added.

But custom strategies are also part of the audit

**Comment by neeksec** [comment]
3rd party developer who extend the strategy should test their contracts and can easily find this behavior in Allo.

If they don't test and make user deposit ETH via `registerRecipient`, it would be the 3rd party developer's fault.

**Comment by imp0wd3r** [comment]
> 3rd party developer who extend the strategy should test their contracts and can easily find this behavior in Allo.
> 
> If they don't test and make user deposit ETH via `registerRecipient`, it would be the 3rd party developer's fault.

This reasoning is far-fetched. A user error should arise from users utilizing functions they shouldn't, whereas this vulnerability results in a potential asset loss from a feature that is intended to function properly.

**Comment by 0xvj** [comment]
My point is that this issue won't allow 3rd party devs to create customized strategies which are able to take native payments once the allo contact is deployed with this issue.
It's not the problem with customized strategies it's the Allo contract itself.

**Comment by MLON33** [comment]
https://github.com/allo-protocol/allo-v2/pull/377

**Comment by Evert0x** [comment]
VII.22: Future issues
> Future issues: Issues that result out of a future integration/implementation that was not intended (mentioned in the docs/README) or because of a future change in the code (as a fix to another issue) are not valid issues.

Planning to reject escalations and keep issue state.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [imp0wd3r](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/20/#issuecomment-1762742335): rejected
