### ISSUE TITLE
coffiasd - ETH may become permanently stuck in the contract

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#202]
coffiasd

high

# ETH may become permanently stuck in the contract

Contract uses `poolAmount` to track the balance of this contract and utilizes `receive{}` to receive ETH tokens. If the `pool.token is the native token and someone directly transfers ETH into this contract, the extra ETH would be permanently stuck in the contract.

## Vulnerability Detail
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L394#L409

DonationVotingMerkleDistributionBaseStrategy contract use poolAmount to track the balance. While creating pool user transfer token into this contract and increase poolAmount via `increasePoolAmount`.  The balance will be reduced during the '_distributeSingle' operation and the 'withdraw' operation.  But contract also use receive{} to receive native token, the received token amounts are not being accumulated, so they cannot be withdrawn during the 'withdraw' operation, resulting in the tokens being stuck in the contract

There is a similar issue in the RFPSimpleStrategy contract withdraw function:
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L295#L301

this is my test case:
```solidity
    function test_canNotWithdraw() public {
        vm.warp(block.timestamp + 31 days);

        uint256 poolAmount = strategy.getPoolAmount();

        uint256 balance = address(strategy).balance;
        
        //poolAmount == balance == 1e18 native token.
        assertEq(poolAmount,balance);

        //send another 1e18 native token to strategy contract.
        address(strategy).call{value:1e18}("");

        //now the balance is 2 * 1e18
        balance = address(strategy).balance;
        assertEq(balance,2 * 1e18);

        //we can't withdraw the balance 2 * 1e18
        vm.expectRevert(INVALID.selector);
        vm.prank(pool_admin());
        strategy.withdraw(2 * 1e18);

        //we can only withdraw 1e18.
        vm.prank(pool_admin());
        strategy.withdraw(1e18);
    }
```
What's more native token comes from payable function like `registerRecipient` and `allocate` not add to poolAmount those token also get stuck in contract

## Impact
ETH may become permanently stuck in the contract 
## Code Snippet
```solidity
    function withdraw(uint256 _amount) external onlyPoolManager(msg.sender) {
        if (block.timestamp <= allocationEndTime + 30 days) {
            revert INVALID();
        }

        IAllo.Pool memory pool = allo.getPool(poolId);

        if (_amount > poolAmount) {
            revert INVALID();
        }

        poolAmount -= _amount;

        // Transfer the tokens to the 'msg.sender' (pool manager calling function)
        _transferAmount(pool.token, msg.sender, _amount);
    }
```

## Tool used

Manual Review

## Recommendation
we should check the contract balance to withdraw token instead of poolAmount

**Comment by neeksec** [comment]
Low/info because sending funds directly to the pool is not the right way to fund a pool. It would be user’s mistake.

But sponsor should take a look and be aware of this.
