### ISSUE TITLE
sandNallani - In the RFP strategies funds can be distributed to recipients with rejected milestones.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#218]
sandNallani

medium

# In the RFP strategies funds can be distributed to recipients with rejected milestones.
In the RFP simple and committee strategies, a pool manager is a trusted role, and is able to reject a user's submitted milestone. This changes the milestone status to rejected. However, this has no effect on the ability to distribute funds to the recipient. 

## Vulnerability Detail

In the `RFPSimpleStrategy`, the poolManager allocates the proposal to a recipient. Following which the recipient submits a  poof of an upcoming milestone. Which changes the status of the milestone to `Pending`. If the pool manager rejects the milestone,  it sets the milestone status to `Rejected`. 

For example:
- Let's say `Alice` registers to build the Dapp for `Bob`.
- `Bob` allocates and accepts Alice as the recipient.
- `Bob` sets milestones at 20%,30%,50%. Initial milestone status is `none` by default.
- `Alice` submits `milestone#1`, which then sets the milestone status to `Pending`.
- `Bob` rejects the milestone, which sets the milestone status to `Rejected` 
-  Assume a case where another pool manager, say `Charlie` isn't aware of `Bob's` transaction to reject the milestone. And proceeds to distribute the funds to `Alice`. The transaction will not revert and `Alice` ends up receiving 20% of the proposal bid in spite of her milestone getting rejected earlier by `Bob`.

https://github.com/allo-protocol/allo-v2/blob/851571c27df5c16f6586ece2a1cb6fd0acf04ec9/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L417

## Impact
This disrupts the stipulated guidelines for the RFP strategies, as the distribution of funds hinges on the recipient's milestone status being marked as `Pending` rather than `Rejected`. Accordingly, fund dispersal should only occur if a milestone hasn't been rejected and proper proof for the milestone's completion has been submitted.
However, this issue has been classified as medium severity since the initiation of fund distribution is contingent upon the actions of the pool manager.

## Code Snippet

```solidity

  function test_rejectMilestone_RecipientStillGetsPaid_PASS() public {
            address recipientId = __register_setMilestones_1_2();
            __allocate(recipientId);
            assertEq(uint8(strategy.getMilestoneStatus(0)), uint8(IStrategy.Status.None));
            assertEq(uint8(strategy.getMilestoneStatus(0)), uint8(IStrategy.Status.None));
            __rejectMilestone();
            assertEq(uint8(strategy.getMilestoneStatus(0)), uint8(IStrategy.Status.Rejected));
            __fundPool();
            vm.expectEmit(true, false, false, true);
            emit Distributed(recipientId, recipientAddress(), 7e17, pool_admin());
            vm.prank(address(allo()));
            strategy.distribute(new address[](0), "", pool_admin());
    }


    function __fundPool() internal returns (address recipientId) {
        vm.deal(pool_admin(), 1e19);
        vm.prank(pool_admin());
        allo().fundPool{value: 1e19}(poolId, 1e19);

    }

    function __rejectMilestone() internal {
        vm.expectEmit();
        emit MilestoneStatusChanged(0, IStrategy.Status.Rejected);
        vm.prank(pool_admin());
        strategy.rejectMilestone(0);
        RFPSimpleStrategy.Milestone memory milestone = strategy.getMilestone(0);
        assertEq(uint8(milestone.milestoneStatus), uint8(IStrategy.Status.Rejected));
    }

```

## Tool used

Foundry
VS Code

## Recommendation

- Consider confirming the milestone submitted by the recipient, ensuring that it aligns with the expected metadata parameters and possesses a `Pending` status following the submission of milestone proof by the recipient.

- Next, ascertain that the milestone has not been marked as `Rejected` by one of the pool managers before proceeding to distribute the funds to the recipient via `RFPSimpleStrategy#_distribute()` or `RFPCommitteeStrategy#_distribute()` methods.

**Comment by cryptonomicon46** [comment]
Escalate
I had a private thread open with the sponsor who said this sounded like a valid issue, hence I submitted it. And would like to have it reconsidered as a valid issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> I had a private thread open with the sponsor who said this sounded like a valid issue, hence I submitted it. And would like to have it reconsidered as a valid issue. 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
