### ISSUE TITLE
nmirchev8 - Creating a Pool Expects Amount Greater than Intended baseFee + amount

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#220]
nmirchev8

medium

# Creating a Pool Expects Amount Greater than Intended baseFee + amount
If baseFee > 0, users should always overpay due to issues within the _createPool function:
```solidity
if (baseFee > 0) {
            // To prevent paying the baseFee from the Allo contract's balance
            // If _token is NATIVE, then baseFee + _amount should be >= than msg.value.
            // If _token is not NATIVE, then baseFee should be >= than msg.value.
            // @audit the rule is that msg.value should always be grater than the necessary amount. 
            // If base fee is 10 and amount is 100, then msg.value of 110 should be enough, but the transaction will revert and will always 
            // expect payment in advance.
            if ((_token == NATIVE && (baseFee + _amount >= msg.value)) || (_token != NATIVE && baseFee >= msg.value)) {
                revert NOT_ENOUGH_FUNDS();
            }

            _transferAmount(NATIVE, treasury, baseFee);
            emit BaseFeePaid(poolId, baseFee);
        }
```
## Vulnerability Detail
The issue lies here: (baseFee + _amount >= msg.value). The comment is misleading because the statement baseFee + _amount should be >= than msg.value is not accurate. If it is greater than msg.value, paying the baseFee would be done from the Allo balance. The same inequality is presented inside the if statement, which defines when to revert. However, using = causes the function to revert every time a user provides exactly the required baseFee, which is not the intended behavior.

## Impact
This issue results in poor user experience and unintended contract behavior. Users are required to pay more from their accounts than necessary.
## Code Snippet
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L473
## Tool used

Manual Review

## Recommendation
The recommendation is to remove the = from inside the if statement:
```solidity
 if ((_token == NATIVE && (baseFee + _amount > msg.value)) || (_token != NATIVE && baseFee > msg.value)) {
                revert NOT_ENOUGH_FUNDS();
            }
```

**Comment by NicolaMirchev** [comment]
Escalate
Issues involving a code error are escalated to a minimum of a 'medium' classification due to their potential impact. While the actual financial impact may be low (just 1 wei of overpayment), the reason for this classification is the divergence from the intended protocol behavior. This deviation can be seen as a disruption of the protocol's established invariants. Invariant, in this context, means that the fee for pool creation should match the provided ETH.

Moreover, the classification has received validation from the sponsor, Kurt, who confirmed that it indeed constitutes a bug.

**Comment by sherlock-admin2** [comment]
> Escalate
> Issues involving a code error are escalated to a minimum of a 'medium' classification due to their potential impact. While the actual financial impact may be low (just 1 wei of overpayment), the reason for this classification is the divergence from the intended protocol behavior. This deviation can be seen as a disruption of the protocol's established invariants. Invariant, in this context, means that the fee for pool creation should match the provided ETH.
> 
> Moreover, the classification has received validation from the sponsor, Kurt, who confirmed that it indeed constitutes a bug.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by neeksec** [comment]
Duplicates of this issue,

#001,#018,#022,#031,#038,#068,#074,#083,#089,#101,#114,#118,#119,#140,#146,#163,#179,#185,#191,#220,#229,#239,#251,#287,#338,#345,#347,#354,#373,#467,#470,#480,#485,#490,#496,#502,#505,#525,#530,#539,#540,#542,#554,#561,#594,#626,#641,#642,#645,#659,#688,#698,#707,#708,#720,#721,#722,#740,#743,#750,#752,#756,#769,#770,#819,#826,#876,#882,#890,#914

Can use this issue for disscussion.

**Comment by marchev** [comment]
The judge's argument here is that if a user adds `1 wei`, it can prevent the DoS.

However, the issue, is that end users aren't aware of the fact that increasing their deposit by just 1 wei would make the deposit succeed. To know this, you'd need to know the implementation of this functionality. Which most users don't.

This basically means that many user might deposit (a lot) more than `1 wei` and this is a bit of an incorrect assumption.

**Comment by nevillehuang** [comment]
Normally, users accidentally sending more native eth are not accepted based on sherlock rules. But in this case, they are forced to, and coupled with a lack of refund mechanism when creating pools, I am inclined to think this is a medium issue, since it is guranteed loss for users funding pool.

**Comment by 0xbtk** [comment]
> Normally, users accidentally sending more native eth are not accepted based on sherlock rules. But in this case, they are forced to, and coupled with a lack of refund mechanism when creating pools, I am inclined to think this is a medium issue, since it is guranteed loss for users funding pool.

Agreed, This issue isn't due to user mistakes and it does have a minor impact. Nonetheless, it affects all creators, making it a valid medium imo. PS – Sending just 1 wei or more isn't a genuine fix; it's just a workaround.

**Comment by 0x00ffDa** [comment]
In support of the initial Low judgment ... and consistency with the current guidelines:

1. Technically, the overpayment would not be a permanent loss of user funds since each could be refunded by Allo owner via `recoverFunds()`. (Of course, that's only practical for a significant amount overpaid.)
2. Bad "user experience" is not generally considered a valid Sherlock finding.

**Comment by nevillehuang** [comment]
Allo owner has no incentive to refund user funds tho, and the “bad user experience” involves sending extra funds then intended.

**Comment by 0xbtk** [comment]
> In support of the initial Low judgment ... and consistency with the current guidelines:
> 
> 1. Technically, the overpayment would not be a permanent loss of user funds since each could be refunded by Allo owner via `recoverFunds()`. (Of course, that's only practical for a significant amount overpaid.)
> 2. Bad "user experience" is not generally considered a valid Sherlock finding.

You are suggesting that the owner should serve as a manual refund system to monitor and reimburse users who overpaid while creating a pool?

**Comment by 0x00ffDa** [comment]
> > In support of the initial Low judgment ... and consistency with the current guidelines:
> > 
> > 1. Technically, the overpayment would not be a permanent loss of user funds since each could be refunded by Allo owner via `recoverFunds()`. (Of course, that's only practical for a significant amount overpaid.)
> > 2. Bad "user experience" is not generally considered a valid Sherlock finding.
> 
> You are suggesting that the owner should serve as a manual refund system to monitor and reimburse users who overpaid while creating a pool?

Not as a solution to the problem. But as an available workaround that reduces the severity of the issue (e.g. until fixed by an upgrade), yes.

**Comment by marchev** [comment]
> > > In support of the initial Low judgment ... and consistency with the current guidelines:
> > > 
> > > 1. Technically, the overpayment would not be a permanent loss of user funds since each could be refunded by Allo owner via `recoverFunds()`. (Of course, that's only practical for a significant amount overpaid.)
> > > 2. Bad "user experience" is not generally considered a valid Sherlock finding.
> > 
> > 
> > You are suggesting that the owner should serve as a manual refund system to monitor and reimburse users who overpaid while creating a pool?
> 
> Not as a solution to the problem. But as an available workaround that reduces the severity of the issue (e.g. until fixed by an upgrade), yes.

Due to the absence of internal accounting mechanism as well as the ability to recover the funds in an all-or-nothing fashion, this is not only impractical, but virtually impossible.

**Comment by neeksec** [comment]
Suggest to keep low.

To workaround this bug, the user don't need to know the code. The protocol can make the user pay extra 1wei of native in the frontend. User signs the tx that the frontend construct.

Extra 1 wei of native token lost is low in impact.

**Comment by marchev** [comment]
@neeksec What if the protocol gets integrated by other protocols? As you are undoubtedly aware, one of the key advantages of DeFi lies in its composability. Are you implying that such a hacky workaround should be adopted by all protocols that integrate Allo?

**Comment by neeksec** [comment]
Who integrate the protocol should read the code and can do the same thing to workaround this.

**Comment by marchev** [comment]
> Who integrate the protocol should read the code and can do the same thing to workaround this.

I kindly disagree with you.

Whoever integrates the protocol should mostly be concerned with the presented contract/API.

It's a fragile premise to expect all protocols that integrate it, to read the code in such a detail and furthermore to find this issue.

**Comment by 0xbtk** [comment]
> Who integrate the protocol should read the code and can do the same thing to workaround this.

That's a lot of workarounds for a wrong operator that can be easily mitigated!

**Comment by marchev** [comment]
> > Who integrate the protocol should read the code and can do the same thing to workaround this.
> 
> 
> 
> That's a lot of workarounds for a wrong operator that can be easily mitigated!

Exactly. It makes absolutely no sense to pile dirty fix on top of dirty fix to workaround what's essentially a deficiency in the current protocol that charges users more than it should.

**Comment by osmanozdemir1** [comment]
I agree with 1 wei is not important at all, and I also agree that it can be solved on the frontend. I want to share the comment I made under my own escalation about solving the issue on the frontend. [Here](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/743#issuecomment-1763303572).

Apart from that, saying the problem can be solved on the frontend for this issue is the same as saying 1 second overlap can be solved on the frontend for these issues: #261, #835. 
The protocol can easily delay the distribution for 1 second on the frontend, and voila! No issue left.
In fact, even the user pushes the distribute button on the frontend in the exact same timestamp, it will still take a few seconds for transaction to be mined and that overlap will never occur. 

To be honest, the current issue being valid or invalid doesn't matter at all because it won't even pay 1 USD with more than 70 duplicates. The thing that matters is being consistent between these issues. If workaround with frontend is acceptable solution, all of these issues should be invalid including the block.timestamp overlap issue and its duplicates. Otherwise, all of them should be valid. Invalidating one of them but validating other is not fair because all of these can be solved on the frontend.

**Comment by nevillehuang** [comment]
> I agree with 1 wei is not important at all, and I also agree that it can be solved on the frontend. I want to share the comment I made under my own escalation about solving the issue on the frontend. [Here](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/743#issuecomment-1763303572).
> 
> Apart from that, saying the problem can be solved on the frontend for this issue is the same as saying 1 second overlap can be solved on the frontend for these issues: #261, #835. The protocol can easily delay the distribution for 1 second on the frontend, and voila! No issue left. In fact, even the user pushes the distribute button on the frontend in the exact same timestamp, it will still take a few seconds for transaction to be mined and that overlap will never occur.
> 
> To be honest, the current issue being valid or invalid doesn't matter at all because it won't even pay 1 USD with more than 70 duplicates. The thing that matters is being consistent between these issues. If workaround with frontend is acceptable solution, all of these issues should be invalid including the block.timestamp overlap issue and its duplicates. Otherwise, all of them should be valid. Invalidating one of them but validating other is not fair because all of these can be solved on the frontend.

Wholeheartedly agree with this, while i understand that there are always work arounds, unless explicitly mentioned by the protocol as a known issue, we shouldn’t invalidate an issue because of that, and we should encourage fixes on contract level instead of relying everything on the front end.

 I will respect what @hrishibhat decides but I agree that if issues like this are invalidated because there are easy “work arounds” then alot of other issues needs to be re-reviwed and reevaluated. Like for example, the issues #261 and #835 mentioned. Also FOT  #19, users can simply not use fot tokens and the protocol can simply include a warning on the front-end. For #699, the front end can simply warn the pool manager to not review a recipient more than once.

**Comment by neeksec** [comment]
What's different between this one and #261, #835 is that,

If you don't workaround this bug by calling with exact `baseFee + _amount` the transaction revert. Funds are not at risk. Sponsor can easily find out this and produce the workaround.

If you don't workaround other bugs you mentioned like #261, #835, funds could be stuck. Sponsor can only find out after damage had been made.

**Comment by Evert0x** [comment]
Core criteria for Medium
> There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost.

You can argue that the potential loss is 1 wei / user. This is not a material amount. 

Planning to reject escalation and keep issue state.

**Comment by marchev** [comment]
@Evert0x as it has been pointed out many times, 1 wei of overpaying is a false assumption. Please see the many comments pointing out why.

**Comment by nevillehuang** [comment]
@Evert0x Another thing to note, I doubt the UI will even allow users to specify just 1 extra wei unless users interact with protocol on contract level.

**Comment by Evert0x** [comment]
UI details / wallet implementations / user behavior assumptions are not relevant to the solidity code. Based on the solidity code it will result in a potential 1 wei loss / user.

**Comment by nevillehuang** [comment]
> UI details / wallet implementations / user behavior assumptions are not relevant to the solidity code. Based on the solidity code it will result in a potential 1 wei loss / user.

Have no more discussions to make as i believe above points are sufficient. Will respect your final decision 👍

**Comment by osmanozdemir1** [comment]
> UI details / wallet implementations / user behavior assumptions are not relevant to the solidity code. Based on the solidity code it will result in a potential 1 wei loss / user.

If user behavior assumptions are not relevant, how do you assume user will only send 1 wei more? This is also an assumption.

If the only truth is solidity code, the function is not working as expected. 

Every solution recommended until this point are based on assumptions. (“User will only send 1 wei extra” or  “user knows how to read solidity code” or “protocol can fix it on the frontend” etc.)

**Comment by Evert0x** [comment]
> If user behavior assumptions are not relevant, how do you assume user will only send 1 wei more? This is also an assumption.

We don't assume the user behavior. The intended design of the protocol is to let the user pay X wei. The actual design is to let the user pay X+1 wei. 

> If the only truth is solidity code, the function is not working as expected.

I agree that the function is not working as intended. However, the discrepancy between the intended design and the actual design is not significant.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [NicolaMirchev](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/220/#issuecomment-1762783843): rejected
