### ISSUE TITLE
adeolu - when funding pool with a fee on transfer token, the strategy contract's tokenBalance is increased with wrong amount.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#250]
adeolu

medium

# when funding pool with a fee on transfer token, the strategy contract's tokenBalance is increased with wrong amount.
when funding pool with a fee on transfer token via `fundPool()` in allo.sol, the strategy contract's tokenBalance is increased with wrong amount. This is because the `amountAfterFee` which is used doesnt consider the tax taken by the fee on transfer token contract during the transfer operation.
## Vulnerability Detail
Since the `amountAfterFee` value is gotten after Allo contract sends the protocol's percentage to the treasury. The `amountAfterFee` will still be further deducted from by the fee on transfer token contract  during the operation. This means that in actual sense a lower amount is actually credited to the receiving pool. But the pool amount is updated with `amountAfterFee` in  the ` _strategy.increasePoolAmount(amountAfterFee);` call. This is wrong and the correct value to update with should be `amountAfterFee - the transfer tax deducted by the token contract`. 

steps to vuln are : 
- pool is to be funded with 100 fee on transfer token. token has a tax of 5% on every transfer.  
- fundPool() is called in allo.sol. percentage fee is 5% in allo so 5 tokens are sent to treasury but after fee on transfer token tax, 4.75 tokens go to treasury while the token contract takes the 0.25%. 
- now `100 - 5 = 95` tokens are left. 95 tokens is the `amountAfterFee` and 95 tokens are to be transferred to the pool strategy contract. Since this is another transfer operation, the token contract takes another 5% tax which is `95 * 5/100 = 4.75`. So in actuality, 95 -4.75 = 90.25 is credited to the pool by the fee on token contract. 
- But this additional tax is not removed from the `amountAfterFee` before it is used to update the `poolAmount` variable in the pool strategy contract. Thus the poolAmount is updated to be 95 instead of 90.25 which is the actual amount of tokens sent to the contract after all fees have been taken. 

## Impact
This bug will mean that the pool's internal token accounting will be larger than actual token balance. During distributions internal accounting will be affected as internal accounting may have a value greater than actual token balance of the pool. 

## Code Snippet
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L339
```solidity
    function fundPool(uint256 _poolId, uint256 _amount) external payable nonReentrant {
        // if amount is 0, revert with 'NOT_ENOUGH_FUNDS()' error
        if (_amount == 0) revert NOT_ENOUGH_FUNDS();

        // Call the internal fundPool() function
        _fundPool(_amount, _poolId, pools[_poolId].strategy);
    }

    function _fundPool(uint256 _amount, uint256 _poolId, IStrategy _strategy) internal {
        uint256 feeAmount;
        uint256 amountAfterFee = _amount;

        Pool storage pool = pools[_poolId];
        address _token = pool.token;

        if (percentFee > 0) {
            feeAmount = (_amount * percentFee) / getFeeDenominator();
            amountAfterFee -= feeAmount;

            _transferAmountFrom(_token, TransferData({from: msg.sender, to: treasury, amount: feeAmount}));
        }

        _transferAmountFrom(_token, TransferData({from: msg.sender, to: address(_strategy), amount: amountAfterFee}));
        _strategy.increasePoolAmount(amountAfterFee);

        emit PoolFunded(_poolId, amountAfterFee, feeAmount);
    }
```
in the snippet above, there is no accomadation for a second tax removal by a fee on transfer token in the `fundPool()`  fcn logic. The possibility of a token taking its own tax on transfer is completely ignored here and the pool strategy contract is updated with the wrong value. 

below is the `increasePoolAmount` fcn in BaseStrategy.sol
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/BaseStrategy.sol#L153
```solidity

    function increasePoolAmount(uint256 _amount) external override onlyAllo {
        _beforeIncreasePoolAmount(_amount);
        poolAmount += _amount;
        _afterIncreasePoolAmount(_amount);
    }
```
## Tool used

Manual Review

## Recommendation
check the contract balances before and after token transfers and use that to determine the actual amount transferred to the pool contract. 

Duplicate of #19

**Comment by adeolu98** [comment]
Escalate

I think my issue has a better description than https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/19, hence mine should be a main issue and 19 a duplicate of mine.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I think my issue has a better description than https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/19, hence mine should be a main issue and 19 a duplicate of mine. 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
