### ISSUE TITLE
marchev - Rebasing tokens' rewards remain locked in strategy contracts

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#308]
marchev

medium

# Rebasing tokens' rewards remain locked in strategy contracts
Rebasing tokens, like Aave's aTokens, gradually increase the balance of each holder over time, thanks to added interest or airdrops. In Allo's built-in strategies, the way accounting is done is static, which means that any accrued interest or newly received tokens from airdrops end up locked in the strategy contract.

Allo's built-in strategies lack a mechanism to account for and retrieve these tokens and thus they would remain stuck forever in the strategy contract.

## Vulnerability Detail
Funding a pool via `Allo#fundPool()` relies on the `_fundPool()` internal function which updates `_strategy`'s balance via `increasePoolAmount(amountAfterFee)`:

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L509-L517

All built-in strategies extend from `BaseStrategy`. Here is what the implementation of `BaseStrategy#increasePoolAmount()` looks like:

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/BaseStrategy.sol#L153-L157

While this accounting approach would work fine with regular tokens, it will fail with rebasing tokens due to the dynamic nature of the rebasing token's `balanceOf()`. Any additional tokens received as interest or as part of an airdrop would not be reflected in `poolAmount` and would thus remain locked in the strategy contract.

## Impact
Any additional rebasing tokens accrued as an interest or received as part of an airdrop would remain stuck in the strategy contract.

## Code Snippet

See above

## Tool used

Manual Review

## Recommendation
This issue could be addressed in different ways:
- Exclude support for rebasing tokens, possibly by maintaining a token blacklist controlled by the protocol owner;
- Enable pool owners to withdraw surplus tokens using a function akin to `Allo#recoverFunds()`;
- Develop a more intricate allocation and distribution logic that accounts for the changing nature of pool amounts;

**Comment by thelostone-mc** [comment]
Rebasing tokens are difficult to handle. Since we use poolAmount instead of the actual balance, newly accrued token will stay in the contract and won'tbe distributed. We don't use the actual balance to prevent from fee skirting.  the poolManager would be able to withdraw the tokens 30 days after the amounts were distributed.
Worst case: there is a withdraw option available to pool managers
