### ISSUE TITLE
0xgoat - Native tokens can get stuck in `QVBaseStrategy` and `QVSimpleStrategy`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#324]
0xgoat

medium

# Native tokens can get stuck in `QVBaseStrategy` and `QVSimpleStrategy`

The [`_transferAmount()`](https://github.com/allo-protocol/allo-v2/blob/851571c27df5c16f6586ece2a1cb6fd0acf04ec9/contracts/core/libraries/Transfer.sol#L87) in `Transfer` does not check that the msg.value is equal to the `_amount` being transferred.  This means that any msg.value sent greater than the `_amount` will stay as a balance in the contract inheriting from `Transfer`.

## Vulnerability Detail

`QVBaseStrategy`'s [`_distribute()`](https://github.com/allo-protocol/allo-v2/blob/851571c27df5c16f6586ece2a1cb6fd0acf04ec9/contracts/strategies/qv-base/QVBaseStrategy.sol#L436) calls this [`_transferAmount()`](https://github.com/allo-protocol/allo-v2/blob/851571c27df5c16f6586ece2a1cb6fd0acf04ec9/contracts/strategies/qv-base/QVBaseStrategy.sol#L456C23-L456C23) and also does not contain a check the the msg.value equals the amount.  This means that if a poolManager were to send a msg.value > the amount during a native token transfer, there will be an excess of the native token in the contract.

There is no `withdraw()` or `recoverFunds()` function in the `QVBaseStrategy` or `QVSimpleStrategy` strategy, which means the funds will be stuck in the contract until they're self-destructed.

## Impact

Medium

## Tool used

Manual Review

## Recommendation

Add `withdraw()` or `recoverFunds()` functions to `QVBaseStrategy` or add a check that msg.value == the amount in [`_transferAmount()`](https://github.com/allo-protocol/allo-v2/blob/851571c27df5c16f6586ece2a1cb6fd0acf04ec9/contracts/core/libraries/Transfer.sol#L87)

**Comment by neeksec** [comment]
User error.
