### ISSUE TITLE
0xkaden - Funding added to QVBaseStrategy after distribution started results in locked tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#348]
0xkaden

medium

# Funding added to QVBaseStrategy after distribution started results in locked tokens

Distribution accounting logic becomes fixed in QVBaseStrategy while it is still possible to fund the pool. The fixed accounting logic results in some of the newly funded tokens to be permanently locked in the contract.

## Vulnerability Detail

Distribution amounts are determined with fixed values for `recipient.totalVotesReceived` and `totalRecipientVotes`. We know these are fixed because they can only be changed during the allocation period. `poolAmount` is also applied to these values to determine payout amounts, but `poolAmount` can be increased at any time with `fundPool`. If we distribute to some or all recipients then further fund the pool (anyone can fund the pool anytime), then some or all of those newly funded tokens will be permanently locked since we can only claim proportional to the amount of recipient votes remaining.

Consider for example the poolAmount has 100e18 tokens and 50% of the totalRecipientVotes have been distributed (50e18 tokens), resulting in the recipients whom those votes belonged to being marked as `paidOut`. Now imagine the pool is funded and the poolAmount is now doubled to 200e18 tokens. The remaining 50% can only be distributed their share of the total votes (100e18 tokens). So all recipients have been distributed to but only 150e18 out of 200e18 tokens have been distributed. Since there's no way to withdraw the tokens or reallocate to distribute further, those 50e18 tokens are permanently locked in the contract.

Note that:
- `QVBaseStrategy._distribute` accepts an array of recipients, and doesn't necessarily distribute to all recipients at once, possibly resulting in a state of partial distribution
- A transaction to fund the pool may have taken a long time to be included in a block, and since anyone can fund the pool, it may have gone unnoticed by the pool manager(s), resulting in funding after partial or complete distribution

## Impact

Tokens are permanently locked in the contract

## Code Snippet

https://github.com/allo-protocol/allo-v2/blob/851571c27df5c16f6586ece2a1cb6fd0acf04ec9/contracts/strategies/qv-base/QVBaseStrategy.sol#L559
```solidity
function _getPayout(address _recipientId, bytes memory)
    internal
    view
    virtual
    override
    returns (PayoutSummary memory)
{
    Recipient memory recipient = recipients[_recipientId];

    // Calculate the payout amount based on the percentage of total votes
    uint256 amount;
    if (!paidOut[_recipientId] && totalRecipientVotes != 0) {
        // @audit recipient.totalVotesReceived and totalRecipientVotes are fixed values after allocation
        //              since poolAmount is not fixed, increases to poolAmount after partial or whole distribution result in lost tokens
        amount = poolAmount * recipient.totalVotesReceived / totalRecipientVotes;
    }
    return PayoutSummary(recipient.recipientAddress, amount);
}
```

## Tool used

Manual Review

## Recommendation

`QVBaseStrategy.increasePoolAmount` should revert after the allocation period has ended. Additionally, since funds can still be transferred to the strategy, emergency withdrawal logic should be included in the contract, ideally only executable after distribution is complete.

Duplicate of #446

**Comment by kadenzipfel** [comment]
Escalate
This is a duplicate of https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/446

**Comment by sherlock-admin2** [comment]
> Escalate
> This is a duplicate of https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/446

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by neeksec** [comment]
Agree with Escalation.

**Comment by Evert0x** [comment]
Planning to accept escalation and duplicate with #446

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #446

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [kadenzipfel](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/348/#issuecomment-1763179766): accepted
