### ISSUE TITLE
chaduke - wrong check in RFPSimpleStrategy.setMilestones() allows one pool manager to overwrite the milestones set by a previous pool manager

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#372]
chaduke

medium

# wrong check in RFPSimpleStrategy.setMilestones() allows one pool manager to overwrite the milestones set by a previous pool manager
For each pool, once a pool manager sets the milestones, the milestones cannot be replaced. This is achieved by the check of ``upcomingMilestone != 0``. Unfortunately, this check will not prevent another pool manager to call ``setMilestones()`` and set new milestones since ``upcomingMilestone`` will not be increased  until ``_distribute()`` is called. 

## Vulnerability Detail

Once a pool's milestones have been set by one pool manager, another pool manager should not replace them. This is supposed to be prevented by the check of ``upcomingMilestone != 0`` in function ``RFPSimpleStrategy.setMilestones()``:

[https://github.com/allo-protocol/allo-v2/blob/0b881ef4a0013d2809374c9ea69f4cf1288dfe62/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L227-L247](https://github.com/allo-protocol/allo-v2/blob/0b881ef4a0013d2809374c9ea69f4cf1288dfe62/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L227-L247)

However, such a check will fail to prevent the overwriting of existing milestones. This is because ``upcomingMilestone`` will not be increased by  ``RFPSimpleStrategy.setMilestones()``, not by ``submitUpcomingMilestone()``, and only by ``_distribute()``:

[https://github.com/allo-protocol/allo-v2/blob/0b881ef4a0013d2809374c9ea69f4cf1288dfe62/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L417-L450](https://github.com/allo-protocol/allo-v2/blob/0b881ef4a0013d2809374c9ea69f4cf1288dfe62/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L417-L450)

This means, even after an upcoming milestone is submitted via ``submitUpcomingMilestone()`` , existing milestones can still be replaced by another pool manager by calling ``RFPSimpleStrategy.setMilestones()`` since variable ``upcomingMilestone`` will always be equal to zero before ``_distributed()`` is called. 

## Impact
One pool manager can overwrite the milestones set by a previous pool manager before ``_distribute()`` is called. A violation of the design principle. 

## Tool used
VSCode

Manual Review

## Recommendation
Set a flag to indicate that milestones have been set, so that another call of  ``RFPSimpleStrategy.setMilestones()`` will fail when the flag is set.

**Comment by jkoppel** [comment]
Escalate.

Watson has misread the implementation of setMilestones. Milestones are appended, not replaced. There is an issue here, but this report completely mischaracterizes it.

**Comment by sherlock-admin2** [comment]
> Escalate.
> 
> Watson has misread the implementation of setMilestones. Milestones are appended, not replaced. There is an issue here, but this report completely mischaracterizes it.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by neeksec** [comment]
Agree with Escalation. This should be invalid and not a dup of #176.

**Comment by Evert0x** [comment]
Planning to accept escalation and remove duplication state.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [jkoppel](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/372/#issuecomment-1762784523): accepted
