### ISSUE TITLE
shirochan - Can create pool with custom strategy without funds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#374]
shirochan

high

# Can create pool with custom strategy without funds
In `Allo.sol`, a user can create a new pool without funds by deploying a malicious strategy that transfers the ETH funds back to the strategy owner via `receive()`. The transfer of funds will be considered successful and the `poolAmount` will get incremented with no issue. 

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L517

## Vulnerability Detail

1. A user can create a pool with a custom malicious strategy `createPoolWithCustomStrategy()`. 
2. This will call `_fundPool()` where the funds will get sent to the strategy.  `_transferAmountFrom(_token, TransferData({from: msg.sender, to: address(_strategy), amount: amountAfterFee}));`
3. The strategy will receive ETH via receive():
```solidity
receive() external payable {
  // Transfer the received Ether to the owner
  payable(owner).transfer(msg.value);
}
```
4. The `poolAmount` will be incremented by `amountAfterFee` with no issue even though the strategy doesn't have the ETH balance.
```solidity
_strategy.increasePoolAmount(amountAfterFee);
```

## Impact
Users will see that the pool has funds via `getPoolAmount()` when it actually doesn't. If they execute `fundPool`, they can lose their funds via `fundPool`. 

## Code Snippet

```solidity 
function _fundPool(uint256 _amount, uint256 _poolId, IStrategy _strategy) internal {
        uint256 feeAmount;
        uint256 amountAfterFee = _amount;

        Pool storage pool = pools[_poolId];
        address _token = pool.token;

        if (percentFee > 0) {
            feeAmount = (_amount * percentFee) / getFeeDenominator();
            amountAfterFee -= feeAmount;

            _transferAmountFrom(_token, TransferData({from: msg.sender, to: treasury, amount: feeAmount}));
        }
            
            // token = NATIVE
>>        _transferAmountFrom(_token, TransferData({from: msg.sender, to: address(_strategy), amount: amountAfterFee})); 
>>        _strategy.increasePoolAmount(amountAfterFee);

        emit PoolFunded(_poolId, amountAfterFee, feeAmount);
    }
```

## Tool used

Manual Review

## Recommendation

To avoid mismatch between the actual Strategy contract balance and `poolAmount`, it's recommended to check the balance and revert if there's a mismatch. 

```solidity
uint256 beforeStrategyBalance = _token == NATIVE ? address(_strategy).balance : IERC20Upgradeable(_token).balanceOf(address(_strategy));

_transferAmountFrom(_token, TransferData({from: msg.sender, to: address(_strategy), amount: amountAfterFee}));
        
uint256 afterStrategyBalance = _token == NATIVE ? address(_strategy).balance : IERC20Upgradeable(_token).balanceOf(address(_strategy));
require(afterStrategyBalance - beforeStrategyBalance == amountAfterFee, "Allo: strategy balance mismatch");

_strategy.increasePoolAmount(amountAfterFee);
```

**Comment by 0xshirochan** [comment]
@sherlock-admin2 I'd appreciate it if you can help me understand why this was excluded. I'd love to learn so that I can avoid these kind of submissions in the future.
