### ISSUE TITLE
nobody2018 - QVSimpleStrategy should add withdraw function for pool manager to prevent the recipient address from being blacklisted

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#478]
nobody2018

medium

# QVSimpleStrategy should add withdraw function for pool manager to prevent the recipient address from being blacklisted

In QVSimpleStrategy and the base class QVBaseStrategy, there is no `withdraw` function provided for the pool manager to withdraw the remaining funds in the contract. If the token is USDC/USDT, which have blacklisted mechanism. If a recipientAddress is blacklisted, transferring to such an address will definitely revert. It is the recipient's own problem that recipientAddress is blacklisted. However, t**hese funds belong to investors and should be withdrawn and returned to them**.

## Vulnerability Detail

After the allocation ends, PoolManager can distribute the token to the recipients through [[Allo.distribute](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L383-L385)](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L383-L385). Its flow is as follows:

```flow
Allo.distribute
  BaseStrategy.distribute
    QVBaseStrategy._distribute
```

In `_distribute`, the payout of each recipient is calculated by `_getPayout`.

```solidity
File: contracts\strategies\qv-base\QVBaseStrategy.sol
436:     function _distribute(address[] memory _recipientIds, bytes memory, address _sender)
......
443:         uint256 payoutLength = _recipientIds.length;
444:         for (uint256 i; i < payoutLength;) {
445:             address recipientId = _recipientIds[i];
446:             Recipient storage recipient = recipients[recipientId];
447: 
448:->           PayoutSummary memory payout = _getPayout(recipientId, "");
449:->           uint256 amount = payout.amount;
......
455:             IAllo.Pool memory pool = allo.getPool(poolId);
456:->           _transferAmount(pool.token, recipient.recipientAddress, amount);
......
464:         }
465:     }
```

L456, if pool.token is USDC/USDT and `recipient.recipientAddress` is blacklisted, `_transferAmount` will revert.

For simplicity, after the allocation ends, pool.token is USDC and poolAmount is 100,000e6. There are a total of 2 recipients (A and B), and they received the same number of votes. Therefore both A and B should get 50,000e6 USDC.

1.  The pool manager calls `distribute` for A. So, A gets 50,000e6 USDC.
2.  The pool manager calls `distribute` for B. This tx will revert since B.recipientAddress is blacklisted. So, 50,000e6 USDC will be stuck in contract forever.

## Impact

Since the current implementation of QVSimpleStrategy does not provide a withdraw function for the pool manager, if the above situation occurs, the token will be stuck in the contract. This is investors' funds and should be able to be withdrawn back to them.

## Code Snippet

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L456

## Tool used

Manual Review

## Recommendation

Add the `withdraw` function for the pool manager. In this way, the pool manager can withdraw token stuck in contract, then manually return them to investors.

**Comment by securitygrid** [comment]
Escalate
According to sherlock rule:

> User Blacklist: User getting blacklisted by a token/contract causing harm only to themselves is not a valid medium/high.

This issue is different with this rule. Funds come from investors rather than blacklisted addresses. If recipient address is blacklisted, funds should be returned to investors.

**Comment by sherlock-admin2** [comment]
> Escalate
> According to sherlock rule:
> 
> > User Blacklist: User getting blacklisted by a token/contract causing harm only to themselves is not a valid medium/high.
> 
> This issue is different with this rule. Funds come from investors rather than blacklisted addresses. If recipient address is blacklisted, funds should be returned to investors.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
Duplicate of #446. All of the root causes are pointing to potential locked funds in QVBaseStrategy, which requires a withdraw function

**Comment by jkoppel** [comment]
Disagree with escalation.  

Compare the following two scenarios:

A. The pool allocates 100 USDC to an address, distributes it to the address, and then the address is blacklisted and the funds are stuck in the blacklisted address.
B. The pool allocates 100 USDC to an address, then the address is blacklisted, and the funds are stuck in the pool.

In both cases, the investors have spent 100 USDC, and the intended recipient cannot use it because they have been blacklisted.  I see no reason for these two scenarios to be treated differently. The root cause is that a recipient has gotten blacklisted and has harmed themself. It should be excluded per Sherlock rules.

The question here is whether the investors are able to claw back funds from a blacklisted address, which is not at all the same as #446.

**Comment by neeksec** [comment]
Suggest to keep invalid.

Agree with @jkoppel's explaination.

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue state as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [securitygrid](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/478/#issuecomment-1762778177): rejected
