### ISSUE TITLE
BenRai - In `DonationVotingMerkleDistributionDirectTransferStrategy` and `DonationVotingMerkleDistributionDirectVaultStrategy` registrations close to the end of the registration period can not be reviewed by a poolManager

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#488]
BenRai

medium

# In `DonationVotingMerkleDistributionDirectTransferStrategy` and `DonationVotingMerkleDistributionDirectVaultStrategy` registrations close to the end of the registration period can not be reviewed by a poolManager

If a user registers close to `registrationEndTime` of a pool, the poolManager will not have enough time to review the registration since `reviewRecipients` can only be called when the registration period is open

## Vulnerability Detail

In `DonationVotingMerkleDistributionDirectTransferStrategy` and `DonationVotingMerkleDistributionDirectVaultStrategy` users can register themselves as potential recipients during the registration period. To become accepted, the registration needs to be reviewed by a poolManager by calling `reviewRecipients`. The problem is that the function `reviewRecipients` has the modifier ` onlyActiveRegistration` meaning it can only be called during the registration periode. If a user registers close to the end of the registration period the pool manager will not have time to review the registration until the registration period ends. 

## Impact

Not all registrations will be reviewed and the purpose of a registration period will be negated

## Code Snippet
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L341-L360

## Tool used

Manual Review

## Recommendation

Consider adding a review period that starts when the registration period starts and ends some time after the registration period is already over. This will give the poolManager enough time to review every registration for the pool.

**Comment by BenRai1** [comment]
Escalate

This issue is not a dublicat of https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/751. https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/751 talks about the start of the allocation in relation to the end of the registration periode.

This issue here is about the ability of the manager to review applications that were submitted close to the end of the registration period. Not being able to review all submitted aplications breaks a core functionality of the protocol.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue is not a dublicat of https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/751. https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/751 talks about the start of the allocation in relation to the end of the registration periode.
> 
> This issue here is about the ability of the manager to review applications that were submitted close to the end of the registration period. Not being able to review all submitted aplications breaks a core functionality of the protocol.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by thelostone-mc** [comment]
similar to #579

**Comment by neeksec** [comment]
Low impact. No fund risk.

**Comment by hrishibhat** [comment]
Agree with Lead 
This may seem like UX problem, but do not see this as a medium-severity issue. Same for #579 
@BenRai1

**Comment by Evert0x** [comment]
Planning to accept escalation and remove duplicate state.

This issue doesn't address a smart contract issue. It's informational as the illustrates how the business logic isn't correct.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [BenRai1](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/488/#issuecomment-1763167316): accepted
