### ISSUE TITLE
tnquanghuy0512 - Pool manager can distribute to rejected milestone in RFPSimpleStrategy and RFPCommitteeStrategy

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#510]
tnquanghuy0512

medium

# Pool manager can distribute to rejected milestone in RFPSimpleStrategy and RFPCommitteeStrategy
Pool manager can distribute to rejected milestone in RFPSimpleStrategy and RFPCommitteeStrategy
## Vulnerability Detail
Function `_distribute()` in RFPSimpleStrategy contract doesn't check if the milestone already got rejected
```solidity
    function _distribute(address[] memory, bytes memory, address _sender)
        internal
        virtual
        override
        onlyInactivePool
        onlyPoolManager(_sender)
    {
        if (upcomingMilestone >= milestones.length) revert INVALID_MILESTONE();

        //<@@ NOTICE not checking the status of the milestone 

        IAllo.Pool memory pool = allo.getPool(poolId);
        Milestone storage milestone = milestones[upcomingMilestone];
        Recipient memory recipient = _recipients[acceptedRecipientId];

        if (recipient.proposalBid > poolAmount) revert NOT_ENOUGH_FUNDS();

        uint256 amount = (recipient.proposalBid * milestone.amountPercentage) / 1e18;

        poolAmount -= amount;
        _transferAmount(pool.token, recipient.recipientAddress, amount);

        milestone.milestoneStatus = Status.Accepted;

        upcomingMilestone++;

        // Emit events for the milestone and the distribution
        emit MilestoneStatusChanged(upcomingMilestone, Status.Accepted);
        emit Distributed(acceptedRecipientId, recipient.recipientAddress, amount, _sender);
    }
```
## Impact
This will make a rejected milestone become accepted, and the fund will send to the recipient
## Code Snippet
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L417C1-L450C6
## Tool used

Manual Review

## Recommendation
Add this line:
```solidity
+    if (milestones[_milestoneId].milestoneStatus != Status.Pending) revert INVALID_MILESTONE();
```

**Comment by Slavchew** [comment]
These are valid dups: #218, #309, #319, #333, #428, #503, #538, #545, #650, #687, #727, #800, #805, #838, #844, #908

**Comment by MLON33** [comment]
https://github.com/allo-protocol/allo-v2/pull/372
