### ISSUE TITLE
0xbepresent - Funds may be trapped in the `QVSimpleStrategy` contract due a blocked `recipient.recipientAddress`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#512]
0xbepresent

medium

# Funds may be trapped in the `QVSimpleStrategy` contract due a blocked `recipient.recipientAddress`

The `recipient.recipientAddress` can block the transfer transactions causing that funds may be trapped in the `QVSimpleStrategy`.

## Vulnerability Detail

Users can register to the `QVSimpleStrategy` using the [QVBaseStrategy::_registerRecipient()](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L369C14-L369C32) function, then the `pool managers` accepts registrants using the [QVBaseStrategy::reviewRecipients()](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L254) function and finally `allocators` allocates votes to the accepted recipients using the [QVSimpleStrategy::_allocate()](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-simple/QVSimpleStrategy.sol#L107) function. The `recipients` payout is [based on the votes casted](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L571) by allocators.

When users register to the pool strategy they [specify the `recipientAddress`](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L408) which [will be used](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L456) if the user gets a payout from the pool. The problem is that the `recipient.recipientAddress` can block the transfer transactions in different circunstanes:

- Token blocklists. `USDC` and `USDT` have a contract level admin controlled address blocklist. If an address is blocked, then transfers to and from that address are forbidden.
- Pausable tokens. Some tokens can be paused by the admin blocking the transactions.

Consider the next scenario:

1. The `strategy pool` is using `USDC` as a token.
2. The `accepted recipient` receives the 90% of votes. He can get the majority payout in [QVBaseStrategy::_distribute()](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L436C14-L436C25) function
3. There are some problems with the `accepted recipient` and his `recipient.recipientAddress` is in the `USDC blocklist`.
4. The transfer transaction will be reverted in the `QVBaseStrategy::_distribute()` [code line 456](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L456):

```solidity
File: QVBaseStrategy.sol
436:     function _distribute(address[] memory _recipientIds, bytes memory, address _sender)
437:         internal
438:         virtual
439:         override
440:         onlyPoolManager(_sender)
441:         onlyAfterAllocation
442:     {
...
...
448:             PayoutSummary memory payout = _getPayout(recipientId, "");
449:             uint256 amount = payout.amount;
450: 
451:             if (paidOut[recipientId] || !_isAcceptedRecipient(recipientId) || amount == 0) {
452:                 revert RECIPIENT_ERROR(recipientId);
453:             }
454: 
455:             IAllo.Pool memory pool = allo.getPool(poolId);
456:             _transferAmount(pool.token, recipient.recipientAddress, amount);
...
...
465:     }
```
5. Those funds will be trapped in the contract because the `recipient.recipientAddress` can't be changed by the `recipient`, there is not function to do that. Additionally there is not `withdraw()` function in the `QVSimpleStrategy` contract that helps the pool managers to withdraw the unclaimed funds.

## Impact

Funds may be trapped in the `QVSimpleStrategy` contract if there are problems in the transfers caused by irregular `recipientAddress`.

## Code Snippet

- [QVBaseStrategy::_registerRecipient()](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L369C14-L369C32)
- [QVBaseStrategy::_distribute()](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L436C14-L436C25)

## Tool used

Manual review

## Recommendation

Consider to add a function which helps the accepted recipient to change his `recipient.recipientAddress` in all strategies.

In the other hand, consider to add a function which helps `pool managers` to withdraw unclaimed funds in the `QVSimpleStrategy` contract. The `DonationVotingMerkleDistributionBaseStrategy` contract has a [withdraw](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L394) function and `RFPSimpleStrategy` contract has a [withdraw](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L295) function.

**Comment by 0xbepresent** [comment]
Escalate

According to sherlock rule:

> User Blacklist: User getting blacklisted by a token/contract causing harm only to themselves is not a valid medium/high.


The rule does not apply in this situation. The blacklisted address is not harming only to the himself (`recipient`), it is harming to the `investors` who deposited those funds, so the sherlock rule *...causing harm only to themselves* is not applied because `investors` can not recover those funds. 

The investors does not have any function that help them to withdraw the funds, that's why I recommended:

> In the other hand, consider to add a function which helps pool managers to withdraw unclaimed funds in the QVSimpleStrategy contract. The DonationVotingMerkleDistributionBaseStrategy contract has a [withdraw](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L394) function and RFPSimpleStrategy contract has a [withdraw](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L295) function.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> According to sherlock rule:
> 
> > User Blacklist: User getting blacklisted by a token/contract causing harm only to themselves is not a valid medium/high.
> 
> 
> The rule does not apply in this situation. The blacklisted address is not harming only to the himself (`recipient`), it is harming to the `investors` who deposited those funds, so the sherlock rule *...causing harm only to themselves* is not applied because `investors` can not recover those funds. 
> 
> The investors does not have any function that help them to withdraw the funds, that's why I recommended:
> 
> > In the other hand, consider to add a function which helps pool managers to withdraw unclaimed funds in the QVSimpleStrategy contract. The DonationVotingMerkleDistributionBaseStrategy contract has a [withdraw](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L394) function and RFPSimpleStrategy contract has a [withdraw](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L295) function.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by neeksec** [comment]
Duplicate of #478. See #478 for validity.

**Comment by Evert0x** [comment]
Planning to reject escalation based on comment in #478

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xbepresent](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/512/#issuecomment-1765070207): rejected
