### ISSUE TITLE
tnquanghuy0512 - Reviewing recipients and registering register happen in the same time range causing missing few last registers to be review in DonationVotingMerkleDistributionBaseStrategy contract

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#514]
tnquanghuy0512

medium

# Reviewing recipients and registering register happen in the same time range causing missing few last registers to be review in DonationVotingMerkleDistributionBaseStrategy contract
Reviewing recipients and registering register happen in the same time range causing missing few last registers to be review in DonationVotingMerkleDistributionBaseStrategy contract
## Vulnerability Detail
Both functions `reviewRecipients` and `_registerRecipient` have the same modifier `onlyActiveRegistration` which is modifier about the time range should be allowed to call the functions
```solidity
   function reviewRecipients(ApplicationStatus[] memory statuses)
        external
        onlyActiveRegistration
        onlyPoolManager(msg.sender)
     { ... }
```
```solidity
    function _registerRecipient(bytes memory _data, address _sender)
        internal
        override
        onlyActiveRegistration
        returns (address recipientId)
    { ... }
```
```solidity
    modifier onlyActiveRegistration() {
        _checkOnlyActiveRegistration();
        _;
    }
```
```solidity

    function _checkOnlyActiveRegistration() internal view {
        if (registrationStartTime > block.timestamp || block.timestamp > registrationEndTime) {
            revert REGISTRATION_NOT_ACTIVE();
        }
    }
```
## Impact
This will make the pool manager don't have enough time to review the registerings that are very close to the deadline. Even if they do, in the last block that contain the last `reviewRecipients()` transaction, it can still has one or few `registerRecipient()` transactions which is impossible for pool manager to review it, making recipients ineligible to get picked

## Code Snippet
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L528C1-L601C6

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L341C1-L360C6

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L214C1-L217C6

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L457C1-L461C6
## Tool used

Manual Review

## Recommendation
Make the new time range for reviewing the recipient after registering phase ended

Duplicate of #751

**Comment by tnquanghuy0512** [comment]
Escalate

This is not a duplicate of #751 which is talking about Allocation can start before registration ends

This is issue about both functions reviewRecipients and _registerRecipient happened in the same time range [registrationStartTime, registrationEndTime], which make the manager can't have enough time to review throroughly some last registrations

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is not a duplicate of #751 which is talking about Allocation can start before registration ends
> 
> This is issue about both functions reviewRecipients and _registerRecipient happened in the same time range [registrationStartTime, registrationEndTime], which make the manager can't have enough time to review throroughly some last registrations

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by tnquanghuy0512** [comment]
I know the escalation time is over but can the judge and sponsor still look at this?

This is not a duplicate of #751 which is talking about Allocation can start before registration ends

This is issue about both functions reviewRecipients and _registerRecipient happened in the same time range [registrationStartTime, registrationEndTime], which make the manager can't have enough time to review throroughly some last registrations
