### ISSUE TITLE
pks_ - Protocol status check would failed when l2 sequencer goes down

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#584]
pks_

medium

# Protocol status check would failed when l2 sequencer goes down

Protocol status check will failed when l2 sequencer goes down.

## Vulnerability Detail

In the current implementation, some functions of this protocol depend on L2 sequencer to check some status, such as allocation is alive or not, or pool is alive or not. However, it's vulnerable when l2 sequencer go down will cause that `block.timestamp` is unusable. Under such conditions, the protocol status check will failed.

L2 chains like arbitrum and optimism upgrade their sequencer occasional, such as the recent [optimism bedrock upgrade](https://cryptopotato.com/optimism-bedrock-upgrade-release-date-revealed/) cause the sequencer can't be able to process transactions for several hours. Or l2 sequencer bug could also cause transactions in stuck, such as [arbitrum sequencer bug](https://beincrypto.com/arbitrum-sequencer-bug-causes-temporary-transaction-pause/). So it's necessary to implement an mechanism to handle this issue in some abnormal conditions.

## Impact

Oracle price check will be failed when l2 sequencer goes down.

## Code Snippet

https://github.com/allo-protocol/allo-v2/blob/0b881ef4a0013d2809374c9ea69f4cf1288dfe62/contracts/strategies/qv-base/QVBaseStrategy.sol#L243

https://github.com/allo-protocol/allo-v2/blob/0b881ef4a0013d2809374c9ea69f4cf1288dfe62/contracts/strategies/qv-base/QVBaseStrategy.sol#L311

https://github.com/allo-protocol/allo-v2/blob/0b881ef4a0013d2809374c9ea69f4cf1288dfe62/contracts/strategies/qv-base/QVBaseStrategy.sol#L319

## Tool used

vscode, Manual Review

## Recommendation

Use ChainLink [sequencer up feed](https://docs.chain.link/data-feeds/l2-sequencer-feeds), consider integrate the up time feed and give contract extra time when l2 sequencer goes down.

**Comment by yuliyu123** [comment]
Escalate

According to [gitcoin doc](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/README.md?plain=1#L11), this protocol deployed to All EVM compatible chain including arbitrum  & optimism, so protocol should consider l2 sequencer invalid case.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> According to [gitcoin doc](https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/README.md?plain=1#L11), this protocol deployed to All EVM compatible chain including arbitrum  & optimism, so protocol should consider l2 sequencer invalid case. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by neeksec** [comment]
Invalid. There's no 'Oracle price check' in this protocol.

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue state as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [yuliyu123](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/584/#issuecomment-1763368183): rejected
