### ISSUE TITLE
BenRai - In `QVBaseStrategy` the same manager can review one applicant multiple times and thereby render the safety measure of `reviewThreshold` useless

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-09-Gitcoin-judging#589]
BenRai

medium

# In `QVBaseStrategy` the same manager can review one applicant multiple times and thereby render the safety measure of `reviewThreshold` useless
In `QVBaseStrategy` potential recipients are reviewed by poolManager. For a recipient to be accepted, the number of managers that review him with a particular status needs to cross the `reviewThreshold`. The problem is that one manager can review a participant multiple times and thereby render the `reviewThreshold` useless.

## Vulnerability Detail

In `QVBaseStrategy` to ensure additional safety, multiple poolManagers need to review one applicant before he can be accepted. The number of revies to a particular recommendation (accepted or rejected ) must be equal or exceed the set `reviewThreshold`. This safeguard it in place to make sure that multiple poolManager take a look at the same recipient. The problem arises from the fact that it is not tracked if a manager already reviewed the recipient or not. This can lead to the situation where the same manager reviews one recipient multiple times and the recipient is thereby accepted or rejected even though not the required number of poolManagers have revied the recipient.

Example:

The `reviewThreshold` for a `QVBaseStrategy` is set to 2. Alice, a pool manager, reviews one batch of recipients and reviews Bob, a potential recipient, as accepted. When reviewing a second batch of recipients she accidently adds the review of Bob to the data again and reviews Bob as accepted again. Now Bob was accepted even though only one poolManager reviewed him an not the recommended two.

## Impact
Recipients are accepted/rejected even though they have not been reviewed by the recommended number of poolManagern

## Code Snippet

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L254-L288

## Tool used

Manual Review

## Recommendation

Track who revied which applicant to make sure that no poolManager reviews an applicant multiple times and thereby bypasses the safety guard of the `reviewThreshold`

**Comment by securitygrid** [comment]
Escalate 
This is invalid. This is Pool manager input mistake.

**Comment by sherlock-admin2** [comment]
> Escalate 
> This is invalid. This is Pool manager input mistake. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by jkoppel** [comment]
This was confirmed by the sponsor.

Quoted in #264: "If they can cast more than 1 vote and force the approval, it would be a bug"

**Comment by jkoppel** [comment]
This was confirmed by the sponsor.

Quoted in #264: "If they can cast more than 1 vote and force the approval, it would be a bug"

**Comment by detectiveking123** [comment]
It was confirmed multiple times by sponsors that managers are a trusted role. This should not be a valid medium. 

<img width="1021" alt="Screen Shot 2023-10-14 at 11 02 15 PM" src="https://github.com/sherlock-audit/2023-09-Gitcoin-judging/assets/143364593/0f939918-772e-4bd3-b727-54a74ee50ab6">

**Comment by jkoppel** [comment]
And it was also confirmed by sponsors that this issue is valid.

<img width="978" alt="Screenshot 2023-10-15 at 12 35 33 PM" src="https://github.com/sherlock-audit/2023-09-Gitcoin-judging/assets/1279592/1730044a-5378-40e8-abd2-8d8f161316b5">

**Comment by 0xnirlin** [comment]
Invalid, considering the sherlock rules. Sponser can have different opinion.

**Comment by neeksec** [comment]
Suggest to keep medium.

Pool managers should be restricted by `reviewThreshold` and breaking it is a security risk.

**Comment by jacksanford1** [comment]
https://github.com/allo-protocol/allo-v2/pull/350

**Comment by Evert0x** [comment]
Planning to accept escalation and make issue invalid.

It's not extremely clear based on the README, but I interpret it as owner=trusted, but the owner is only expected to do execute on these 3 tasks
- recover funds from Allo.sol
- flag contracts as cloneable
- set the base fee, percent fee , registry address and treasury address

In the next section the pool manager role is defined
> Pool Manager Users who manage funds within specific pools. They can allocate and distribute funds according to the pool's strategy

I would assume the pool manager is not trusted in that case, but based on the PUBLIC discord clarification, it's clear the role is considered trusted
> They are expected to be trusted role and they would not mis-manage the funds in the pool.

With this comment, I can understand why other Watsons didn't submit this issue.

@jkoppel sought clarification in DM, but it contradicts the publicly available information. That's why I think it's unfair to other Watsons to reward this issue. 

Section III.6 
> Discord messages or DM screenshots are not considered sources of truth while judging an issue/escalation especially if they are conflicting with the contest README.

**Comment by osmanozdemir1** [comment]
Does “trusted” mean managers will never make a mistake or does it mean they will not act malicious intentionally?

I always thought trusted meant the second one. They won’t be malicious by intention. They won’t add the same recipient again and again knowing they already added that recipient. Trusted means this (at least I thought so). The scenario in this issue and in some other issues show how it can be mistakenly added even if managers are trusted. I don’t think this is invalid and don’t think a trusted manager is a super-manager.

**Comment by jack-the-pug** [comment]
Not Fixed.

One manager can still reject many times:

https://github.com/allo-protocol/allo-v2/blob/fix-review/contracts/strategies/qv-base/QVBaseStrategy.sol#L287-L290

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [securitygrid](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/589/#issuecomment-1762762914): accepted
