### ISSUE TITLE
MohammedRizwan - Incorrect initialization of `Allo.sol` contract and other issues

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#64]
MohammedRizwan

medium

# Incorrect initialization of `Allo.sol` contract and other issues
Incorrect initialization of `Allo` contract

## Impact

The `Allo.sol` contract inherits `ReentrancyGuardUpgradeable`  contracts but does not invoke the individual initialzer during its own initialization. 

```Solidity
contract Allo is IAllo, Native, Transfer, Initializable, Ownable, AccessControl, ReentrancyGuardUpgradeable, Errors {
```

Due to which the state of `ReentrancyGuardUpgradeable` contract remains uninitialized.

```Solidity
File: allo-v2/contracts/core/Allo.sol

    function initialize(address _registry, address payable _treasury, uint256 _percentFee, uint256 _baseFee)
        external
        reinitializer(1)
    {
        // Initialize the owner using Solady ownable library
        _initializeOwner(msg.sender);

        // Set the address of the registry
        _updateRegistry(_registry);

        // Set the address of the treasury
        _updateTreasury(_treasury);

        // Set the fee percentage
        _updatePercentFee(_percentFee);

        // Set the base fee
        _updateBaseFee(_baseFee);
    }
```

Due to this issue, In ReentrancyGuardUpgradeable the `_status` storage variable is never initialized and the `_status` must be set for the correct working of `nonReentrant` 

```Solidity
File: contracts/security/ReentrancyGuardUpgradeable.sol

    function __ReentrancyGuard_init() internal onlyInitializing {
        __ReentrancyGuard_init_unchained();
    }

    function __ReentrancyGuard_init_unchained() internal onlyInitializing {
        _status = _NOT_ENTERED;
    }
```

For the correct working of `nonReentrant`, the `_status` must be equal to `_NOT_ENTERED` which is the first condition of `_nonReentrantBefore()` which can be checked as below.

```Solidity
File: contracts/security/ReentrancyGuardUpgradeable.sol

    modifier nonReentrant() {
        _nonReentrantBefore();
        _;
        _nonReentrantAfter();
    }

    function _nonReentrantBefore() private {
>>      // On the first call to nonReentrant, _status will be _NOT_ENTERED
        require(_status != _ENTERED, "ReentrancyGuard: reentrant call");

        // Any calls to nonReentrant after this point will fail
        _status = _ENTERED;
    }

    function _nonReentrantAfter() private {
        // By storing the original value once again, a refund is triggered (see
        // https://eips.ethereum.org/EIPS/eip-2200)
        _status = _NOT_ENTERED;
    }
```

Therefore `__ReentrancyGuard_init()` must be initialized in `Allo.initialize()` function for correct initialization.

Another issue is, `Allo.sol` is an upgradeable smart contract and therefore to avoid any compatibility issues instead of `AccessControl`, the contract must used `AccessControlUpgradeable.sol` contract from openzeppelin. The other imported contracts from openzeppelin are upgradeable expect the AccessControl.sol. 

If the normal AccessControl.sol contract is used in an upgradeable contract, you will not be able to upgrade the contract. This is because the normal AccessControl.sol contract is not designed to be upgraded.

When you upgrade a contract, you are essentially replacing the old contract code with new code. However, the normal AccessControl.sol contract does not have a mechanism for upgrading the roles that have been granted to accounts. This means that if you upgrade a contract that uses the normal AccessControl.sol contract, the roles that have been granted to accounts will be lost.

To avoid this problem, you should use the AccessControlUpgradeable.sol contract in your `Allo.sol` contract. The AccessControlUpgradeable.sol contract module is designed to be upgraded, and it has a mechanism for preserving the roles that have been granted to accounts.

In addition, openzeppelin states,

> Initializer functions are not linearized by the compiler like constructors. Because of this, each __{ContractName}_init function embeds the linearized calls to all parent initializers.

Therefore, to mitigate the issues the recommendations should be considered.

## Code Snippet
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L38

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L87-L105

## Tool used
Manual Review

## Recommendation

```diff

- import "openzeppelin-contracts/contracts/access/AccessControl.sol";
+ import "openzeppelin-contracts-upgradeable/contracts/access/AccessControlUpgradeable.sol";

- contract Allo is IAllo, Native, Transfer, Initializable, Ownable, AccessControl, ReentrancyGuardUpgradeable, Errors {
+ contract Allo is IAllo, Native, Transfer, Initializable, Ownable, AccessControlUpgradeable, ReentrancyGuardUpgradeable, Errors {


   // some code


    function initialize(address _registry, address payable _treasury, uint256 _percentFee, uint256 _baseFee)
        external
        reinitializer(1)
    {
        // Initialize the owner using Solady ownable library
        _initializeOwner(msg.sender);

        // Set the address of the registry
        _updateRegistry(_registry);

        // Set the address of the treasury
        _updateTreasury(_treasury);

        // Set the fee percentage
        _updatePercentFee(_percentFee);

        // Set the base fee
        _updateBaseFee(_baseFee);

+      __AccessControl_init();                         @audit // since we are inheriting the AccessControlUpgradeable and __AccessControl_init is an empty function and does not required to be initialize and it is optional but for better clarity it is shown here

+      __ReentrancyGuard_init();                   @audit // now the ReentrancyGuard will be initialized with status as _NOT_ENTERED
    }
```

**Comment by 0xRizwan** [comment]
@neeksec 
This issue is a duplicate of #852. sponsor confirmed this issue.
