### ISSUE TITLE
honeymewn - Overlapping registration and fund allocation times might result in an unfair competition

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#686]
honeymewn

medium

# Overlapping registration and fund allocation times might result in an unfair competition
MerkleRoot and QV strategies have a registration and allocation time windows which might overlap. One of the implications of this is unfair competition since upon resubmission recipient will have to wait to get an approval first before becoming eligible for funding.

## Vulnerability Detail

```solidity
    function _isPoolTimestampValid(
        uint64 _registrationStartTime,
        uint64 _registrationEndTime,
        uint64 _allocationStartTime,
        uint64 _allocationEndTime
    ) internal view {
        if (
            block.timestamp > _registrationStartTime || _registrationStartTime > _registrationEndTime
                || _registrationStartTime > _allocationStartTime || _allocationStartTime > _allocationEndTime
                || _registrationEndTime > _allocationEndTime
        ) {
            revert INVALID();
        }
    }
```

Merkle:

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L496-L509

QV voting:

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/qv-base/QVBaseStrategy.sol#L335-L348

There's nothing preventing a pool owner from creating a pool with overlapping registration and allocation windows. While it may see ok at the first glance there are some serious downsides of this approach which are:
1. If a recipient comes up with a better proposal and resubmit they won't be able to get the funds since pool managers have to reapprove them first. With a high enough backlog of submissions this might take some time for pool managers to sort out. An allocator (sponsor) will see the project is not approved yet and might decide to back other projects instead.
2. While the doc is not clear about this it seems Metadata has a link to project's landing page / whitepaper
https://github.com/allo-protocol/allo-contracts/blob/main/docs/MetaPtrProtocol.md. Since it can be changed by a recipient during registration phase (which can overlap with allocation) this might put sponsors in a really uncomfortable situation, i.e they're unhappy with the new proposal but they have already allocated funds (say via direct transfer). 

## Impact
- Unfair competition. Recipients who resubmit will get less time for funding.
- Recipients might reapply with a completely different application. Existing allocators might be unhappy about it but funds were already sent, i.e merkle direct transfer strategy.

## Tool used

Manual Review

## Recommendation

In my opinion the registration and funding windows should not overlap. There's a set deadline and finite amount of capital from sponsors and if a project is not eligible due to resubmission it'll be at an unfair disadvantage. Potentially not raising enough capital to complete the project. 

Duplicate of #751

**Comment by 0xSulpiride** [comment]
Escalate

**Comment by sherlock-admin2** [comment]
> Escalate

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by thelostone-mc** [comment]
Duplicate of #579

**Comment by neeksec** [comment]
Void escalation.

**Comment by Evert0x** [comment]
Planning to reject escalation as there is no argument to respond to.

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #751

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xsulpiride](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/686/#issuecomment-1764827354): rejected
