### ISSUE TITLE
shogoki - Creating a pool with baseFee can revert if amount is set to correct value.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#720]
shogoki

medium

# Creating a pool with baseFee can revert if amount is set to correct value.

When creating a pool and there is a `baseFee` to be paid, it can revert if the amount is set correctly.

## Vulnerability Detail

in the `createPool` function there can be a baseFee, which is to be charged. This is done in the NATIVE token. As the `_transferAmountFrom` function is checking against the `msg.value` for the transferred amount only. To account for the case if the pool token is the native token there is a check for the `msg.value` to be greater than the amount and baseFee. 

```solidity  
            if ((_token == NATIVE && (baseFee + _amount >= msg.value)) || (_token != NATIVE && baseFee >= msg.value)) {
                revert NOT_ENOUGH_FUNDS();
```
 
However this check is also reverting if the `msg.value`  is set to the exact right  amount.

## Impact

CreatePool Transaction is reverting even if the correct amount is set.

## Code Snippet

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L473-L475

## Tool used

Manual Review

## Recommendation

Change the check for the revert from `>=` to `>`

**Comment by Shogoki** [comment]
Escalate

I think this should be valid. 
As it breaks an intended core functionality of the contract: creating a pool by paying the specified amount + fee.

This is not a user input error, as the user paid the correct amount, but the contract still reverts.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I think this should be valid. 
> As it breaks an intended core functionality of the contract: creating a pool by paying the specified amount + fee.
> 
> This is not a user input error, as the user paid the correct amount, but the contract still reverts.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by neeksec** [comment]
Duplicate of #220. See #220 for validity.

**Comment by Evert0x** [comment]
Planning to reject escalation as this issue is invalid and we don't accept duplication requests with invalid issues.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Shogoki](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/720/#issuecomment-1762887494): rejected
