### ISSUE TITLE
0xRstStn - function _createPool in Allo.sol requires value to be greater than baseFee

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#750]
0xRstStn

medium

# function _createPool in Allo.sol requires value to be greater than baseFee
When creating a new pool, under function _**_createPool**_ in _**Allo.sol**_ , if there is a base fee (i.e. baseFee > 0), the creator of the pool is required to send more ETH than the baseFee amount.

## Vulnerability Detail
The amount of ETH to be sent when invoking _**createPool**_ (and hence _**_createPool**_) is required to be greater than the _**baseFee**_. When creating a pool and not adding any amount to the pool, **_msg.value_** should be equal to the _**baseFee.**_ The amount in excess gets locked in _**Allo.sol**_ and can only be recovered by the Allo owner by invoking **_recoverFunds_**.

## Impact
Users have to spend more ETH than **_baseFee_** in order to create a pool. 

## Code Snippet
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/6430c8004017e96ae2f5aac365bdefd0b6eeea72/allo-v2/contracts/core/Allo.sol#L469-L478

## Tool used
Manual Review.

## Recommendation
Change the condition to:
` if(
       (_token == NATIVE && (baseFee + _amount > msg.value)) ||
       (_token != NATIVE && baseFee > msg.value)
      ) {
                revert NOT_ENOUGH_FUNDS();`
         }

**Comment by 0xRstStn** [comment]
Escalate

This is not the intended behavior of the contract. 
Judge justification states that it could be avoided by the user by sending an extra 1wei of Native but how can the user know he has to send more than the stated ``amount``? If the user sends the stated ``amount``, transaction will revert without the user knowing the reason.

Note: This issue has A LOT of duplicates , see comment in https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/220

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is not the intended behavior of the contract. 
> Judge justification states that it could be avoided by the user by sending an extra 1wei of Native but how can the user know he has to send more than the stated ``amount``? If the user sends the stated ``amount``, transaction will revert without the user knowing the reason.
> 
> Note: This issue has A LOT of duplicates , see comment in https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/220

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by neeksec** [comment]
Duplicate of #220. See #220 for validity.
