### ISSUE TITLE
mahyar - poolAmount is not reduced after distribution in QV Strategy

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#76]
mahyar

high

# poolAmount is not reduced after distribution in QV Strategy
https://github.com/allo-protocol/allo-v2/blob/851571c27df5c16f6586ece2a1cb6fd0acf04ec9/contracts/strategies/qv-base/QVBaseStrategy.sol#L436-L465

`poolAmount` (balance of contract) is not reduced after distribution in QV Strategy contract

## Vulnerability Detail

In  Strategy  contracts whenever the contract receives funds, the sent amount value gets added to `poolAmount` var to cache balance of the strategy also whenever funds go out from contract (distribute/withdraw) the  `poolAmount` is reduced.
this is handled in all of strategy contracts **except [QVBaseStrategy](https://github.com/allo-protocol/allo-v2/blob/main/contracts/strategies/qv-base/QVBaseStrategy.sol) contract**  which doesn't reduce the `poolAmount` in `_distribute` function.

In this strategy poolAmount is used to calculate the amount that should be paid to target recipient via internal call to `_getPayout` function, after it calculated the amount it transfers the amount to recipient but it doesn't reduce the `poolAmount`.

If poolAmount is 100 USDC and 40 USDC is distributed to a recipient the poolAmount will still 100 USDC while contract's balance is 60 USDC and `_getPayout` will return bigger value for next distributions.

## Impact

This leads to some recipients get paid more funds that they dont't deserve and some don't even get anything since the `_getPayout`  returns bigger value but it reverts because lack of balance while transfering the assets.

## Code Snippet
_distribute function 
```solidity
File: allo-v2\contracts\strategies\qv-base\QVBaseStrategy.sol
436:     function _distribute(address[] memory _recipientIds, bytes memory, address _sender)
437:         internal
438:         virtual
439:         override
440:         onlyPoolManager(_sender)
441:         onlyAfterAllocation
442:     {
443:         uint256 payoutLength = _recipientIds.length;
444:         for (uint256 i; i < payoutLength;) {
445:             address recipientId = _recipientIds[i];
446:             Recipient storage recipient = recipients[recipientId];
447: 
448:             PayoutSummary memory payout = _getPayout(recipientId, "");
449:             uint256 amount = payout.amount;
450: 
451:             if (paidOut[recipientId] || !_isAcceptedRecipient(recipientId) || amount == 0) {
452:                 revert RECIPIENT_ERROR(recipientId);
453:             }
454: 
455:             IAllo.Pool memory pool = allo.getPool(poolId);
456:             _transferAmount(pool.token, recipient.recipientAddress, amount);
457: 
458:             paidOut[recipientId] = true;
459: 
460:             emit Distributed(recipientId, recipient.recipientAddress, amount, _sender);
461:             unchecked {
462:                 ++i;
463:             }
464:         }
465:     }
```
_getPayout function:
```solidity
File: allo-v2\contracts\strategies\qv-base\QVBaseStrategy.sol
559:     function _getPayout(address _recipientId, bytes memory)
560:         internal
561:         view
562:         virtual
563:         override
564:         returns (PayoutSummary memory)
565:     {
566:         Recipient memory recipient = recipients[_recipientId];
567: 
568:         // Calculate the payout amount based on the percentage of total votes
569:         uint256 amount;
570:         if (!paidOut[_recipientId] && totalRecipientVotes != 0) {
571:             amount = poolAmount * recipient.totalVotesReceived / totalRecipientVotes;
572:         }
573:         return PayoutSummary(recipient.recipientAddress, amount);
574:     }
```

## Tool used

Manual Review

## Recommendation
Reduce the the `poolAmount` by the amount returned from _getPayout function.

**Comment by thelostone-mc** [comment]
> invalid, QVBaseStrategy are designed to distribute once

+1
