### ISSUE TITLE
jah - the rejected milestone can still take the milestone funds out

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#844]
jah

high

# the rejected milestone can still take the milestone funds out
the rejected milestone can still withdraw the funds if he is the **upcomingmilestone**
## Vulnerability Detail
the function **rejectMilestone** is used to reject a milestone and the only thing the function do is change the status to rejected and the function **distribution** doesn't check about the status of the milestone so if the rejected milestone is the **upcomingmilestone** he can still withdraw the funds
## Impact
loss of fund
## Code Snippet
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L283
## Tool used

Manual Review

## Recommendation
in the internal function _distribute add a check which insure that the status of the **upcomingmilestone** is not rejected

**Comment by Demelew** [comment]
Escalate
 i disagree with this it is technically a bug the function  rejectMilestone is used to reject a milestone but the code is not doing it correctly so it is not possible to stop a milestone from distributing

**Comment by sherlock-admin2** [comment]
> Escalate
>  i disagree with this it is technically a bug the function  rejectMilestone is used to reject a milestone but the code is not doing it correctly so it is not possible to stop a milestone from distributing 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by thelostone-mc** [comment]
Fixed via https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/510

**Comment by neeksec** [comment]
I still believe it's manager's operational fault to first reject a milestone and then distribute it.

**Comment by Demelew** [comment]
well the are rejecting the milestone because they are mistaken  and now they are trying to prevent there mistake but they really cant

**Comment by Evert0x** [comment]
Duplicate of #727

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [demelew](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/844/#issuecomment-1764809129): rejected
