### ISSUE TITLE
0x00ffDa - A milestone with payout of 0 can block all further milestone distributions in a RFP allocation strategy

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#846]
0x00ffDa

medium

# A milestone with payout of 0 can block all further milestone distributions in a RFP allocation strategy
In `RFPSimpleStrategy` and `RFPCommitteeStrategy` contracts, a milestone with `amountPercentage` of 0 (i.e. no payout) will block all further milestone distributions to the recipient if the pool token reverts on transfer amount 0.

## Vulnerability Detail
**First, why is this issue valid despite Sherlock rules excluding non-standard ERC20 behavior?**
While the Sherlock rules currently exclude "issues related to tokens with non-standard behaviors", [the rules also state that](https://docs.sherlock.xyz/audits/judging/judging#iii.-some-standards-observed) "In case of conflict between information in the README, vs Sherlock rules, the README overrides Sherlock rules." And the contest README specifically says that all ERC20 with non-standard behavior are supported:

> "Q: Do you expect to use any of the following tokens with non-standard behaviour with the smart contracts?
> Yes as we support all ERC20 tokens."

Milestones are gating mechanisms for paying RFP implementers for work in stages. Milestones are processed sequentially in `RFPSimpleStrategy` contracts (and `RFPCommitteeStrategy`, by inheritance) such that only the next milestone, indicated by the `upcomingMilestone` variable, can be accepted by a pool manager and the associated funds paid to the recipient. The amount distributed to a recipient for a milestone is determined by `amountPercentage` stored for that milestone.

If a milestone is defined for some action / condition that must be satisfied but there is no associated payment, the milestone's  `amountPercentage` is 0. Upon calling `distribute()` to accept this milestone and advance to the next, the pool will attempt to transfer 0 pool tokens to the recipient. If the pool token is [one that reverts on a transfer of amount 0 (e.g. LEND)](https://github.com/d-xo/weird-erc20#revert-on-zero-value-transfers), the `upcomingMilestone` variable is not incremented, leaving the contract state stuck at this milestone which can never be surpassed.

## Impact
Pool fails to distribute all funds to the accepted recipient due to a bricked state. A pool manager cannot modify the `upcomingMilestone` variable to skip the problematic milestone. The only workaround is for a pool manager to withdraw the pool funds and perform all remaining distributions manually, abandoning the broken contract entirely.

## Code Snippet
Relevant part of [`RFPSimpleStrategy._distribute()` function](https://github.com/allo-protocol/allo-v2/blob/851571c27df5c16f6586ece2a1cb6fd0acf04ec9/contracts/strategies/rfp-simple/RFPSimpleStrategy.sol#L417) that transfers funds for a milestone and advances to the next milestone:
```solidity
        // Get the pool, subtract the amount and transfer to the recipient
        poolAmount -= amount;
        _transferAmount(pool.token, recipient.recipientAddress, amount);

        // Set the milestone status to 'Accepted'
        milestone.milestoneStatus = Status.Accepted;

        // Increment the upcoming milestone
        upcomingMilestone++;
```

## Tool used

Found by manual review. Verified using [token-tester](https://github.com/bEsPoKeN-tOkEns/token-tester) with [RevertZero](https://github.com/d-xo/weird-erc20/blob/main/src/RevertZero.sol) token.

## Recommendation
To resolve this and any other potential instances of the 0-transfer problem, add a check in [Transfer.sol](https://github.com/allo-protocol/allo-v2/blob/851571c27df5c16f6586ece2a1cb6fd0acf04ec9/contracts/core/libraries/Transfer.sol#L28) library functions that skips ERC20 transfers of amount 0.

**Comment by thelostone-mc** [comment]
This is a valid report. Ideally we should ensure no milestones are set with amount percentage as 0 
Would label it as a low severity

**Comment by jacksanford1** [comment]
https://github.com/allo-protocol/allo-v2/pull/373
