### ISSUE TITLE
0xnirlin - Not using the upgradable variant of access control in upgradable contracts at multiple places.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#852]
0xnirlin

high

# Not using the upgradable variant of access control in upgradable contracts at multiple places.
While writing the upgradable contracts, unlike solady there are separate contracts to support upgradibility in openzeppelin libraries, but the project is using the non upgradable variant.
## Vulnerability Detail
Openzeppelin provides the up-gradable variant of standard contracts, if those are not used the whole upgrade-abilitiy thing for the contract be bricked and it would not be fully upgradeable.

Solady have by default support for upgrades in each contract, while openzeppelin have done those separately.

Use the AccessControlUpgrdable at following places:

Allo.sol
```solidity
contract Allo is IAllo, Native, Transfer, Initializable, Ownable, AccessControl, ReentrancyGuardUpgradeable, Errors {
```

Registery.sol

```solidity
contract Registry is IRegistry, Native, AccessControl, Transfer, Initializable, Errors {
```

## Impact
Smart contracts will not be upgradable
## Code Snippet
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Allo.sol#L38
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/core/Registry.sol#L40
## Tool used

Manual Review

## Recommendation
Use the `AccessControlUpgradable` instead

**Comment by 0xnirlin** [comment]
Escalate

Unlike solady, openzeppelin's each smart contract does not work with both upgradable and non upgradable smart contract. As the contract is upgradable, use the upgradable variant of access control i.e accessControlUpgrdable.sol

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Unlike solady, openzeppelin's each smart contract does not work with both upgradable and non upgradable smart contract. As the contract is upgradable, use the upgradable variant of access control i.e accessControlUpgrdable.sol

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by thelostone-mc** [comment]
This is valid. Would mark it as a low severity issue which needs to be fixed

**Comment by 0xRizwan** [comment]
#64 is a duplicate and highlighting similar issue.

**Comment by AhmadDecoded** [comment]
How is it low severity issue if it hinders the upgradibility, should be a valid medium. Also such issues in past have been marked medium.

**Comment by 0xnirlin** [comment]
IMO should be a valid medium, breaks the assumption of roles upgradibility, issue #64 talks in detail about it.

**Comment by neeksec** [comment]
I've compared the source code of [AccessControl](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.1/contracts/access/AccessControl.sol#L50) and [AccessControlUpgradable](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.9.2/contracts/access/AccessControlUpgradeable.sol#L51). 

The upgradable version provides safe measures like storage gap and restricting functions with `onlyInitializing`. I don't see how the non-upgradable version prevent contract from upgrading. 

I think `AccessControl` used still works and the contracts using it still can be upgraded, only having more risk of storage variable collsion.

**Comment by jacksanford1** [comment]
https://github.com/allo-protocol/allo-v2/pull/374

**Comment by 0xnirlin** [comment]
@neeksec haven't the storage gap vulnerability in itself have been categorized as medium in past which is the subset of the problem here too, look at the following examples:

https://solodit.xyz/issues/m-16-corruptible-upgradability-pattern-sherlock-notional-notional-git
https://solodit.xyz/issues/m-07-no-storage-gap-for-upgradeable-contracts-code4rena-rubicon-rubicon-contest-git

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue state.

The issue is informational/low, no funds are at risk.

**Comment by Evert0x** [comment]
@AhmadDecoded read point 15 for more info https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ahmaddecoded](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/852/#issuecomment-1763317747): rejected
