### ISSUE TITLE
jah - a malicious user can stop other from receiving there fund

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-09-Gitcoin-judging#860]
jah

high

# a malicious user can stop other from receiving there fund
a malicious user can stop other from receiving there distribution  by changing the  **recipient.recipientAddress 
## Vulnerability Detail**
anyone can change  **recipient.recipientAddress** by being the member of **recipientid** and when distributing the funds it uses the **merkleroot** to verify the amount and the  **recipient.recipientAddress**  is not changed if it is changed and it is not if the **merkproof** is not correct it will revert the internal function     _distribute which calls     **_distributesingle** and  in this function it will pass the **amount**, **receipientaddress** to the  merkproof to check and if it si false it will revert
## Impact
stop other from claiming there funds 

## Code Snippet
https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L783
## Tool used

Manual Review

## Recommendation
stop from updating the recipientaddress twice

**Comment by Demelew** [comment]
Escalate 
if the Boolean value **useRegistryAnchor** is set to **false** anyone can change the register recipient  so if we ever changed the  the recipient id receiver address  when distributing  the  function **_validateDistribution**  on line 783 will RETURN FALSE AND IF THE  RETURN VALUE IS FALSE  the else statement will be executed which will revert and the funds will not be transferred to the real user

**Comment by sherlock-admin2** [comment]
> Escalate 
> if the Boolean value **useRegistryAnchor** is set to **false** anyone can change the register recipient  so if we ever changed the  the recipient id receiver address  when distributing  the  function **_validateDistribution**  on line 783 will RETURN FALSE AND IF THE  RETURN VALUE IS FALSE  the else statement will be executed which will revert and the funds will not be transferred to the real user   

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by neeksec** [comment]
> anyone can change recipient.recipientAddress by being the member of recipientid

This is one attacking himself.

**Comment by Demelew** [comment]
no if the **useRegistryAnchor**  Boolean is set to false anyone can change the recipient.recipientAddress OF ANY recipientid  so anyone can stop the process

**Comment by neeksec** [comment]
This is not true. This check prevents that,

https://github.com/sherlock-audit/2023-09-Gitcoin/blob/main/allo-v2/contracts/strategies/donation-voting-merkle-base/DonationVotingMerkleDistributionBaseStrategy.sol#L557-L559

**Comment by Demelew** [comment]
the check is not efficient we can bypass the check   the check
`if (isUsingRegistryAnchor && !_isProfileMember(recipientId, _sender)) {
                revert UNAUTHORIZED();
            }`
we can controls  the value of **isUsingRegistryAnchor** because in line 551 the Boolean is set to true if  **registryAnchor** is set to a non zero address 
`            isUsingRegistryAnchor = registryAnchor != address(0);
`  
and we have to  make the registryAnchor an address(0) when passing the data argument

**Comment by neeksec** [comment]
if `isUsingRegistryAnchor` is set to false, then `recipientId` will be set to `_sender` and cannot be arbitrarily controled.

`recipientId = isUsingRegistryAnchor ? registryAnchor : _sender;`

**Comment by Demelew** [comment]
OH YEAH SORRY 
\

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue state as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [demelew](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/860/#issuecomment-1763739936): rejected
